// Les textes de la reprise de la v10 (brique 62) : ce que le rapport dit d'une écriture qui ne se
// reprendrait pas telle quelle.

import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'reprise.montant': 'un montant ne se lit pas au millime',
  'reprise.date': 'la date ne se lit pas',
  'reprise.hors_exercice': 'la date tombe hors de l\'exercice ({du} au {au})',
  'reprise.journal': 'le journal « {journal} » n\'existe pas sur la plateforme (VT, AC, BQ, CA, OD, PAIE, AN)',
  'reprise.deux_lignes': 'une écriture a au moins deux lignes',
  'reprise.un_cote': 'une ligne va au débit ou au crédit, jamais aux deux ni à aucun',
  'reprise.compte': 'le compte « {compte} » ne s\'écrit pas en chiffres',
  'reprise.desequilibre': 'elle n\'est pas équilibrée : {debit} au débit, {credit} au crédit',
  'reprise.sans_numero': 'validée sans numéro',
  'reprise.numero_pris': 'le numéro {numero} est déjà celui d\'une autre écriture',
  'reprise.lettre_forme': 'la lettre « {lettre} » ne s\'écrit pas de une à cinq lettres, de A à Z',
  'reprise.lettre_comptes': 'la lettre {lettre} relie plusieurs comptes ({comptes}) : un lettrage tient sur un seul compte',
  'reprise.lettre_brouillard': 'la lettre {lettre} touche une écriture au brouillard : on ne lettre que des écritures validées',
  'reprise.lettre_seule': 'la lettre {lettre} ne relie qu\'une écriture : un lettrage en relie au moins deux',
  'reprise.lettre_solde': 'la lettre {lettre} ne se solde pas : il reste {reste}',
  'reprise.releve_solde': 'un solde de ce relevé ne se lit pas au millime',
  'reprise.releve_compte': 'ce relevé n\'a pas de compte bancaire qui s\'écrive en chiffres',
  'reprise.releve_vide': 'ce relevé ne porte aucune ligne',
  'reprise.releve_double': 'ce relevé est deux fois dans le livre (le même fichier)',
  'reprise.releve_ligne': 'la ligne {n} de ce relevé n\'a pas de date ou de montant lisible au millime',
  'reprise.releve_face': 'la ligne {n} de ce relevé est rapprochée d\'une ligne d\'écriture qui n\'est pas dans le livre sur le compte {compte}',
  'reprise.releve_face_double': 'la ligne {n} de ce relevé est rapprochée d\'une ligne d\'écriture qui répond déjà d\'une autre ligne de relevé',
  'reprise.releve_boucle': 'ce relevé ne se boucle pas : {debut} au départ, {mouvements} de mouvements, et il annonce {fin}',
  'reprise.immo_libelle': 'un bien n\'a pas de libellé',
  'reprise.immo_compte': 'un compte de ce bien (immobilisation, amortissement, dotation, subvention) ne s\'écrit pas en chiffres',
  'reprise.immo_date': 'la date de mise en service ou de sortie de ce bien ne se lit pas',
  'reprise.immo_montant': 'un montant de ce bien (valeur, résiduelle, TVA, subvention, prix de sortie) ne se lit pas au millime',
  'reprise.immo_duree': 'la durée de ce bien ne se lit pas (en années, au centième au plus)',
  'reprise.immo_taux': 'le taux dégressif de ce bien ne se lit pas (quatre décimales au plus)',
  'reprise.immo_ecriture': 'la dotation ou la sortie de {annee} de ce bien renvoie à une écriture qui n\'est pas dans le livre',
  'reprise.immo_genre': 'l\'écriture {piece}, liée à ce bien en {annee}, n\'est ni sa dotation ni sa sortie',
  'reprise.revision_periode': 'une révision de ce livre n\'est ni l\'exercice {annee} ni l\'un de ses mois',
  'reprise.revision_double': 'la révision de cette période est deux fois dans le livre',
  'reprise.revision_forme': 'la révision de cette période ne se lit pas telle quelle ({champ})',
  'reprise.question_periode': 'une question de ce livre n\'est ni sur l\'exercice {annee} ni sur l\'un de ses mois',
  'reprise.question_texte': 'une question n\'a pas de texte',
  'reprise.question_compte': 'le compte d\'une question ne s\'écrit pas en chiffres',
  'reprise.question_montant': 'le montant d\'une question ne se lit pas au millime',
  'reprise.question_statut': 'l\'état d\'une question n\'est pas connu (ouverte, envoyée, répondue ou close)',
  'reprise.question_reponse': 'une question dite répondue n\'a pas de réponse, ou l\'inverse',
  'reprise.question_envois': 'une question dite envoyée n\'a pas d\'envoi, ou l\'inverse',
  'reprise.declaration_periode': 'une déclaration de ce livre n\'est pas un mois de l\'exercice {annee}',
  'reprise.declaration_double': 'la déclaration de ce mois est deux fois dans le livre',
  'reprise.declaration_case': 'la case « {case} » n\'est pas une case de la déclaration',
  'reprise.declaration_montant': 'la case « {case} » ne se lit pas au millime',
  'reprise.declaration_jour': 'le jour du dépôt ou du paiement de cette déclaration ne se lit pas',
  'reprise.declaration_payee': 'cette déclaration est payée sans être déposée',
  'reprise.declaration_ecriture': 'l\'écriture du mois de cette déclaration n\'est pas dans le livre',
  'reprise.inventaire_double': 'le livre porte plus d\'un inventaire pour l\'exercice',
  'reprise.inventaire_date': 'l\'inventaire ne se date pas dans l\'exercice {annee}',
  'reprise.inventaire_compte': 'le compte de stock de l\'inventaire ne s\'écrit pas en chiffres',
  'reprise.inventaire_ligne': 'la ligne {n} de l\'inventaire n\'a pas de désignation, ou sa quantité ou son coût ne se lit pas',
  'reprise.inventaire_ecriture': 'l\'écriture de variation de l\'inventaire n\'est pas dans le livre',
  'reprise.dossier_nom': 'un dossier n\'a pas de nom (ou un nom de plus de deux cents caractères)',
  'reprise.dossier_matricule': 'le matricule fiscal « {matricule} » ne se lit pas : sept chiffres, une lettre autre que I, O ou U, puis code TVA, catégorie et établissement (1234567A/A/M/000)',
  'reprise.dossier_matricule_double': 'le matricule fiscal {matricule} est celui de deux dossiers du fichier',
  'reprise.dossier_honoraires': 'les honoraires de ce dossier ne se lisent pas au millime',
  'reprise.dossier_fiche': 'la fiche de ce dossier ne se reprend pas telle quelle ({champ})',
});
