// Les textes du module Caisse (14 § 5) : ce que font ses gestes, et ce qu'il refuse.

import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'geste.caisse.ticket.encaisser': 'encaisser un ticket de caisse',
  'caisse.pas_un_ticket': 'seul un ticket de caisse (une vente au comptoir, sans numéro) s\'encaisse ici : rien n\'a été vendu',
  'caisse.paiement_manquant': 'le paiement du ticket ({paye}) n\'est pas son total ({total}) : rien n\'a été vendu',
  'caisse.client_inconnu': 'le client choisi n\'est pas dans le dossier : rien n\'a été vendu. Recharge la page',
  'caisse.comptoir': 'Vente au comptoir',
  'geste.caisse.session.ouvrir': 'ouvrir la caisse (sa session, avec le fond de caisse)',
  'geste.caisse.session.fermer': 'fermer la caisse (compter le tiroir, le Z)',
  'geste.caisse.voir': 'voir la caisse et ses Z',
  'caisse.nom_par_defaut': 'Caisse 1',
  'caisse.fermee': 'la caisse est fermée : ouvre-la avec ton fond de caisse avant d\'encaisser. Rien n\'a été vendu',
  'caisse.ouverte_ailleurs': 'la caisse est ouverte sur un autre appareil ({appareil}, par {qui}) : une caisse n\'est tenue que par un appareil à la fois. Ferme-la là-bas, puis ouvre-la ici. Rien n\'a été vendu',
  'caisse.deja_ouverte': 'la caisse est déjà ouverte ({appareil}, par {qui}, depuis {depuis}) : on la ferme avant de la rouvrir',
  'caisse.sans_appareil': 'la caisse s\'ouvre depuis un appareil connecté (un navigateur, l\'application) : rien n\'a été ouvert',
  'caisse.pas_ouverte': 'la caisse n\'est pas ouverte : il n\'y a rien à fermer',
  'caisse.fermer_ailleurs': 'la caisse se ferme sur l\'appareil qui la tient ({appareil}), ou par le propriétaire ou un administrateur',
  'caisse.session_inconnue': 'la session de caisse de ce ticket n\'existe pas dans cette entreprise : rien n\'a été enregistré',
  'caisse.pas_ce_poste': 'ce ticket a été encaissé sur la caisse d\'un autre appareil : seul l\'appareil qui la tenait le remet. Rien n\'a été enregistré',
  'geste.caisse.relais': 'changer de caissier sur le poste de la caisse',
  'geste.caisse.code.poser': 'poser son code de caisse (4 chiffres)',
  'caisse.code_forme': 'le code de caisse a 4 chiffres, ni plus ni moins : rien n\'a été changé',
  'caisse.code_trop_simple': 'le code {code} se devine trop vite (chiffres répétés ou qui se suivent) : choisis-en un autre. Rien n\'a été changé',
  'caisse.relais_pas_ce_poste': 'on ne change de caissier que sur l\'appareil qui tient la caisse, sur « mon ordinateur » : rien n\'a changé',
  'caisse.relais_sans_code': 'cette personne ne prend pas la caisse par un code : elle doit être caissier (sans être propriétaire, administrateur ni paie) et avoir posé son code de caisse. Rien n\'a changé',
  'caisse.relais_code_faux': 'ce code ne correspond pas : la caisse reste à {qui}',
  'geste.caisse.ticket.rendre': 'rendre un article sur un ticket de caisse (un avoir, l\'argent rendu)',
  'geste.caisse.code_responsable.poser': 'poser son code de responsable (4 chiffres), qui approuve un retour à la caisse',
  'caisse.fermee_retour': 'la caisse est fermée : l\'argent rendu sort du tiroir, ouvre-la d\'abord. Rien n\'a été rendu',
  'caisse.ouverte_ailleurs_retour': 'la caisse est ouverte sur un autre appareil ({appareil}, par {qui}) : l\'argent rendu sort de son tiroir, le retour se fait là-bas. Rien n\'a été rendu',
  'caisse.retour_pas_un_ticket': 'un retour se fait sur un ticket de caisse encaissé, ligne à ligne : rien n\'a été rendu',
  'caisse.retour_ligne': 'une ligne rendue n\'est pas une ligne du ticket {numero} (le même article, au même prix) : rien n\'a été rendu',
  'caisse.retour_trop': 'on ne rend pas plus de « {article} » que le ticket {numero} n\'en a vendu, retours déjà faits compris : rien n\'a été rendu',
  'caisse.retour_mode': 'l\'argent se rend en espèces, par carte ou par chèque : rien n\'a été rendu',
  'caisse.retour_paiement': 'l\'argent rendu doit être le montant de l\'avoir ({net}), aujourd\'hui : rien n\'a été rendu',
  'caisse.retour_compte': 'le compte d\'où sort l\'argent rendu n\'est pas dans le dossier : rien n\'a été rendu. Recharge la page',
  'caisse.retour_sans_responsable': 'un retour se fait avec le code d\'un responsable présent (le propriétaire ou un administrateur) : rien n\'a été rendu',
  'caisse.retour_responsable_inconnu': 'cette personne n\'approuve pas à la caisse : elle doit être propriétaire ou administrateur et avoir posé son code de responsable, et le retour se fait sur l\'appareil de la caisse. Rien n\'a été rendu',
  'caisse.retour_code_faux': 'ce code de responsable ne correspond pas : rien n\'a été rendu',
  'caisse.remise_sans_responsable': 'une remise de {taux} % dépasse ce que la caisse permet sans accord ({plafond} %) : il faut le code d\'un responsable présent (le propriétaire ou un administrateur). Rien n\'a été vendu',
  'caisse.remise_responsable_inconnu': 'cette personne n\'approuve pas à la caisse : elle doit être propriétaire ou administrateur et avoir posé son code de responsable, et la vente se fait sur l\'appareil de la caisse. Rien n\'a été vendu',
  'caisse.remise_code_faux': 'ce code de responsable ne correspond pas : rien n\'a été vendu',
  'caisse.montant_illisible': 'le montant « {valeur} » ne se lit pas : tape-le comme 150 ou 150,500',
});
