// Les textes du module Comptabilité (14 § 5) : ce que font ses gestes, et les libellés des
// écritures (écrits dans la langue de l'entreprise au moment où l'écriture s'écrit, comme la v10).

import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'geste.compta.livres.voir': 'voir les livres, la balance et le grand livre',
  'geste.compta.ecritures.valider': 'valider les livres : une période, une écriture ou un lot ; contre-passer, extourner',
  'geste.compta.ecritures.saisir': 'saisir une écriture au brouillard, la modifier, la supprimer',
  'geste.compta.lettrage.poser': 'lettrer les écritures d\'un compte, délettrer',
  'geste.compta.declarations.preparer': 'préparer la déclaration du mois, la marquer déposée et payée, en écrire l\'écriture',
  'compta.champ.periode': 'un mois : AAAA-MM',
  'geste.compta.liasse.preparer': 'préparer la liasse de l\'année : ses retraitements et son taux d\'impôt',
  'compta.champ.taux': 'un taux en pourcentage (« 25 » ou « 22,5 »)',
  'compta.libelle.extourne': 'Extourne de {numero}',
  'compta.champ.ecriture': 'une écriture : sa date, son journal, au moins deux lignes',
  'compta.champ.montant': 'un montant en dinars, sans signe (« 1191,000 »)',
  'compta.champ.montant_signe': 'un montant en dinars, signé au sens de la banque (« -1250,500 » : l\'argent sort)',
  'compta.champ.empreinte': 'l\'empreinte du fichier : 64 caractères hexadécimaux',
  'compta.champ.annee': 'une année sur quatre chiffres',
  'compta.champ.ids': 'la liste des écritures (de 1 à 500)',
  'compta.champ.revision': 'la révision du brouillard que tu as vue',
  'compta.champ.lettre': 'une à cinq lettres, de A à Z',
  'compta.champ.jusqua': 'le dernier jour de la période à valider (AAAA-MM-JJ)',
  'compta.libelle.contre_passation': 'Contre-passation de {numero}',
  'compta.champ.journal': 'un journal : VT, AC, BQ, CA, OD, PAIE ou AN',
  'compta.champ.compte': 'un numéro de compte (des chiffres)',
  'compta.champ.fin_avant_debut': 'la fin de la période ne peut pas précéder son début',
  'compta.libelle.facture': 'Facture {numero} — {client}',
  'compta.libelle.avoir': 'Avoir {numero} — {client}',
  'compta.libelle.ventes': '{libelle} (HT {taux} %)',
  'compta.libelle.tva': 'TVA {taux} % — {numero}',
  'compta.libelle.timbre': 'Timbre fiscal {numero}',
  'compta.libelle.change': 'Écart de change {numero}',
  'compta.libelle.regularisation': 'Régularisation de la retenue {facture} (avoir {numero})',
  'compta.libelle.reglement': 'Règlement {numero} — {client}',
  'compta.libelle.remboursement': 'Remboursement {numero} — {client}',
  'compta.libelle.retenue_subie': 'Retenue à la source subie {numero}',
  'compta.libelle.gain_change': 'Gain de change — {libelle}',
  'compta.libelle.perte_change': 'Perte de change — {libelle}',
  'compta.libelle.achat.facture': 'Achat {numero} — {fournisseur}',
  'compta.libelle.achat.depense': 'Dépense {numero} — {fournisseur}',
  'compta.libelle.achat.avoir': 'Avoir fournisseur {numero} — {fournisseur}',
  'compta.libelle.achat.acompte': 'Acompte versé {numero} — {fournisseur}',
  'compta.libelle.sans_numero': '(sans numéro)',
  'compta.libelle.frais': 'Frais accessoires {numero}',
  'compta.libelle.tva_deductible': 'TVA déductible {numero}',
  'compta.libelle.imputation': 'Imputation acompte {acompte} sur {numero}',
  'compta.libelle.reglement_fournisseur': 'Règlement fournisseur {numero} — {fournisseur}',
  'compta.libelle.remboursement_fournisseur': 'Remboursement {numero} — {fournisseur}',
  'compta.libelle.retenue_operee': 'Retenue à la source opérée {numero}',
  'compta.libelle.paie': 'Salaires {periode}',
  'compta.libelle.salaires_verses': 'Salaires versés — {periode}',
  'compta.libelle.avances': 'Avances sur salaire — {periode}',
});
