// Les textes du dossier v10 tenu par le serveur (14 § 5) : ses refus, et ce que font ses gestes.

import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'quarantaine.deja_decidee': 'cette remise a déjà été acceptée ou rejetée : rien n\'a changé',
  'quarantaine.change_depuis': 'elle a changé depuis sur le serveur : la version du serveur est gardée, celle de l\'appareil reste avec la remise',
  'v10.conflit': 'quelqu\'un d\'autre vient de modifier ce dossier : recharge-le, tes changements ne sont pas perdus tant que la fenêtre reste ouverte',
  'v10.emission_par_le_serveur': 'une facture ou un avoir ne s\'émet qu\'avec le bouton « Émettre » : c\'est le serveur qui lui donne son numéro',
  'v10.avoir_ne_se_modifie_plus': 'l\'avoir {numero} est émis : il ne se modifie plus',
  'v10.avoir_ne_s_efface_pas': 'l\'avoir {numero} est émis : il ne s\'efface jamais',
  'v10.annulee': 'la facture {numero} est émise : elle ne s\'annule pas, on la corrige par un avoir (un avoir total la solde)',
  'v10.reglement_sur_brouillon': 'un paiement ne s\'enregistre que sur une facture émise : émets-la d\'abord',
  'v10.reglement_sans_identifiant': 'un paiement de la facture {numero} n\'a pas d\'identifiant : rien n\'a été enregistré',
  'v10.reglement_double': 'deux paiements de la facture {numero} portent le même identifiant : rien n\'a été enregistré',
  'v10.reglement_date': 'un paiement de la facture {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.reglement_montant': 'un paiement de la facture {numero} n\'a pas de montant : rien n\'a été enregistré',
  'v10.reglement_decimales': 'un paiement en {devise} se compte à {decimales} décimales au plus ({montant}) : rien n\'a été enregistré',
  'v10.reglement_cours': 'le taux du jour d\'un paiement de la facture {numero} est illisible : rien n\'a été enregistré',
  'v10.reglement_ailleurs': 'ce paiement appartient déjà à une autre facture : rien n\'a été enregistré',
  'v10.salarie_enfants': 'le nombre d\'enfants à charge de {salarie} doit être un nombre entier entre 0 et 99 : rien n\'a été enregistré',
  'v10.salarie_date': 'la date d\'entrée ou de sortie de {salarie} n\'est pas une date valable : rien n\'a été enregistré',
  'v10.bulletin_salarie': 'un bulletin de {periode} nomme un salarié qui n\'existe plus : rien n\'a été enregistré',
  'v10.bulletin_periode': 'un bulletin de {salarie} n\'a pas de mois valable : rien n\'a été enregistré',
  'v10.bulletin_sans_bareme': 'le bulletin de {salarie} ({periode}) n\'a pas gardé le barème qui l\'a calculé : ouvre-le et enregistre-le à nouveau. Rien n\'a été enregistré',
  'v10.bulletin_bareme': 'le barème du bulletin de {salarie} ({periode}) est illisible (un taux entre 0 et 100 à quatre décimales au plus, un montant au millime) : rien n\'a été enregistré',
  'v10.bulletin_saisie': 'le bulletin de {salarie} ({periode}) a un brut, des jours, une prime ou une retenue illisible (un montant positif au millime, des jours au millième) : rien n\'a été enregistré',
  'v10.bulletin_situation': 'le bulletin de {salarie} ({periode}) compte des enfants à charge qui ne sont pas un nombre entier entre 0 et 99 : rien n\'a été enregistré',
  'v10.bulletin_ecart': 'le serveur ne trouve pas les mêmes montants que l\'écran pour le bulletin de {salarie} ({periode}) : {montant} vaut {ecran} à l\'écran, {serveur} au serveur. Rien n\'a été enregistré',
  'v10.bulletin_brut': 'le bulletin de {salarie} ({periode}) a un salaire brut nul une fois les absences déduites : ouvre-le et corrige ses jours d\'absence, ou supprime-le. Rien n\'a été enregistré',
  'v10.bulletin_net': 'le bulletin de {salarie} ({periode}) aurait un net négatif, ses retenues dépassent le salaire : ouvre-le et réduis une retenue (une avance se rembourse sur plusieurs mois), ou supprime-le. Rien n\'a été enregistré',
  'v10.avance_illisible': 'une avance sur salaire n\'a pas de date ou de montant valable (un montant positif, trois décimales au plus) : rien n\'a été enregistré',
  'v10.bulletin_paye_le': 'la date de paiement du bulletin de {salarie} ({periode}) n\'est pas une date valable : rien n\'a été enregistré',
  'v10.achat_reglement_sans_identifiant': 'un règlement de l\'achat {numero} n\'a pas d\'identifiant : rien n\'a été enregistré',
  'v10.achat_reglement_double': 'deux règlements de l\'achat {numero} portent le même identifiant : rien n\'a été enregistré',
  'v10.achat_reglement_date': 'un règlement de l\'achat {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.achat_reglement_montant': 'un règlement de l\'achat {numero} n\'a pas de montant : rien n\'a été enregistré',
  'v10.achat_reglement_cours': 'le taux du jour d\'un règlement de l\'achat {numero} est illisible : rien n\'a été enregistré',
  'v10.achat_reglement_ailleurs': 'ce règlement appartient déjà à un autre achat : rien n\'a été enregistré',
  'v10.achat_nature': 'l\'achat {numero} n\'est ni une facture, ni une dépense, ni un avoir, ni un acompte : rien n\'a été enregistré',
  'v10.achat_date': 'l\'achat {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.achat_echeance': 'l\'échéance de l\'achat {numero} n\'est pas une date valable : rien n\'a été enregistré',
  'v10.achat_devise': 'la devise {devise} de l\'achat {numero} n\'est pas encore connue du serveur : rien n\'a été enregistré',
  'v10.achat_cours': 'l\'achat {numero} est en {devise} : indique son taux de change (combien vaut 1 {devise} en dinars). Rien n\'a été enregistré',
  'v10.achat_frais': 'les frais de l\'achat {numero} en {devise} se comptent à {decimales} décimales au plus : rien n\'a été enregistré',
  'v10.achat_retenue': 'le taux de retenue de l\'achat {numero} doit être un pourcentage entre 0 et 100, à quatre décimales au plus : rien n\'a été enregistré',
  'v10.achat_ligne': 'la ligne {rang} de l\'achat {numero} a une quantité (trois décimales au plus), un prix (six) ou un taux de TVA (entre 0 et 100) illisible : rien n\'a été enregistré',
  'v10.achat_fournisseur': 'le fournisseur de l\'achat {numero} n\'existe plus : choisis-en un autre. Rien n\'a été enregistré',
  'v10.achat_lie_introuvable': 'l\'achat {numero} est rattaché à une pièce qui n\'existe plus : ouvre-le et retire le rattachement. Rien n\'a été enregistré',
  'v10.achat_lie_devise': 'l\'achat {numero} se rattache à une pièce en {devise} : un avoir ou un acompte se rattache à une pièce de SA devise. Rien n\'a été enregistré',
  'v10.achat_lie_nature': 'l\'achat {numero} se rattache à une pièce qui n\'est ni une facture ni une dépense : rien n\'a été enregistré',
  'v10.achat_rattache': 'un avoir ou un acompte est rattaché à cet achat : détache-le (ou supprime-le) d\'abord, puis supprime l\'achat. Rien n\'a été supprimé',
  'v10.emise_ne_se_modifie_plus': 'la facture {numero} est émise : elle ne se modifie plus, on la corrige par un avoir',
  'v10.emise_ne_s_efface_pas': 'la facture {numero} est émise : elle ne s\'efface jamais, on la corrige par un avoir',
  'ventes.encours_accord': '{client} dépasserait son encours autorisé de {depasse} ({encours} déjà dus, {piece} pour cette facture, {plafond} autorisés) : il faut l\'accord du propriétaire ou d\'un administrateur. Demande-le ; la facture s\'émettra une fois l\'accord donné',
  'ventes.remise_accord': '{client} : la remise de {taux} dépasse les {seuil} permis sans accord : il faut l\'accord du propriétaire ou d\'un administrateur. Demande-le ; la facture s\'émettra une fois l\'accord donné',
  'ventes.remise_ligne_accord': '{client} : « {ligne} » est vendu {taux} sous son prix, au-delà des {seuil} permis sans accord : il faut l\'accord du propriétaire ou d\'un administrateur. Demande-le ; la facture s\'émettra une fois l\'accord donné',
  'achats.commande_accord': 'la commande {numero} chez {fournisseur} fait {montant} hors taxes, au-delà des {seuil} permis sans accord : elle part avec l\'accord du propriétaire ou d\'un administrateur. Enregistre-la en brouillon et demande l\'accord ; elle partira une fois l\'accord donné',
  'achats.accord_inutile': 'cette commande reste sous le montant permis sans accord : elle part sans accord',
  'achats.seule_commande': 'seule une commande fournisseur, avec son fournisseur, demande cet accord',
  'ventes.accord_inutile': 'cette facture reste dans l\'encours autorisé de son client : elle s\'émet sans accord',
  'ventes.accord_deja_decide': 'cette demande a déjà été décidée : rien n\'a changé',
  'ventes.accord_le_sien': 'on ne décide pas sa propre demande : un autre responsable accorde ou refuse',
  'v10.partie.documents': 'les devis, factures et bons',
  'v10.partie.recurring': 'les contrats récurrents',
  'v10.partie.templates': 'les modèles de documents',
  'v10.partie.snippets': 'les textes prédéfinis',
  'v10.partie.projects': 'les affaires',
  'v10.partie.clients': 'les clients',
  'v10.partie.catalog': 'le catalogue',
  'v10.partie.priceLists': 'les listes de prix',
  'v10.partie.suppliers': 'les fournisseurs',
  'v10.partie.purchases': 'les achats',
  'v10.partie.supplierOrders': 'les commandes fournisseurs',
  'v10.partie.receptions': 'les réceptions',
  'v10.partie.accounts': 'les comptes de trésorerie',
  'v10.partie.movements': 'les mouvements de trésorerie',
  'v10.partie.stockAdjustments': 'les mouvements de stock',
  'v10.partie.serials': 'les numéros de série',
  'v10.partie.depots': 'les dépôts',
  'v10.partie.employees': 'les salariés',
  'v10.partie.payslips': 'les bulletins de paie',
  'v10.partie.leaves': 'les congés',
  'v10.partie.advances': 'les avances sur salaire',
  'v10.partie.socialFilings': 'les déclarations sociales',
  'v10.partie.assets': 'les immobilisations',
  'v10.partie.ecrituresOD': 'les opérations diverses',
  'v10.partie.fiscalFilings': 'les échéances fiscales déposées',
  'v10.partie.clotures': 'les clôtures d\'exercice',
  'v10.partie.fiscalDeadlines': 'les échéances fiscales',
  'v10.partie.deleted': 'les pièces supprimées',
  'v10.partie.conflictArchive': 'les versions écartées',
  'v10.partie.company': 'la fiche de la société',
  'v10.partie.version': 'les réglages de l\'application',
  'v10.partie.counters': 'les compteurs de numéros',
  'v10.partie.demo': 'les réglages de l\'application',
  'v10.partie.exemple': 'les réglages de l\'application',
  'v10.partie.expenseCategories': 'les catégories de charges',
  'v10.partie.fixedCategories': 'les catégories de charges',
  'v10.partie.depotPrincipalNom': 'le nom du dépôt principal',
  'v10.partie.payrollSettings': 'les barèmes de paie',
  'v10.partie.vatCarryIn': 'le crédit de TVA reporté',
  'v10.partie.closedUntil': 'la clôture des périodes',
  'v10.partie.closureLog': 'la clôture des périodes',
  'v10.partie.auxiliaires': 'les comptes auxiliaires',
  'v10.partie.autre': 'cette partie du dossier',
  'v10.partie_interdite': 'ton rôle ne permet pas d\'enregistrer {partie} dans le dossier de l\'entreprise : rien n\'a été enregistré. Demande au propriétaire ou à un administrateur',
  'v10.supprimer_le_sien': '{piece} a été fait par {auteur} : seul son auteur, le propriétaire ou un administrateur le supprime. Rien n\'a été supprimé',
  'v10.supprimer_sans_auteur': '{piece} date d\'avant que SkanFact retienne qui fait chaque pièce : seul le propriétaire ou un administrateur le supprime. Rien n\'a été supprimé',
  'v10.ce_brouillon': 'ce brouillon',
  'v10.ticket_par_la_caisse': 'un ticket de caisse s\'encaisse depuis la caisse, avec sa série : rien n\'a été émis',
  'boutique.un_prix': 'une ligne a un prix TTC (prixUnitaireTTC) ou un prix HT (prixUnitaire) : l\'un des deux, jamais les deux',
  'boutique.quantite': 'la ligne « {designation} » : aucun prix HT à six décimales ne redonne son montant pour cette quantité ; envoie-la en plusieurs lignes',
  'boutique.note_paiement': 'Boutique en ligne',
  'boutique.ligne_arrondi': 'Arrondi',
  'boutique.note_remboursement': 'Remboursement d\'un retour de la boutique en ligne',
  'boutique.objet_retour': 'Retour de la commande {reference} ({retour})',
  'boutique.retour_trop': 'ce retour ferait {retour} alors qu\'il ne reste que {possible} de la commande à rendre : rien n\'a été enregistré',
  'boutique.rembourse_trop': 'le client n\'a payé que {possible} de plus que ce qu\'il doit : on ne lui rend pas {montant}. Rien n\'a été enregistré',
  'boutique.retour_lignes': 'une partie de cette commande est déjà rendue : envoie les lignes de ce retour (toute la commande ne se rend plus d\'un coup)',
  'boutique.retour_timbre': 'le timbre de cette commande n\'est pas à rendre : sa facture n\'en a pas, ou un autre retour l\'a déjà rendu',
  'boutique.montant_nul': 'un montant de zéro ne se paie ni ne se rend',
  'boutique.ecart_retour': 'l\'avoir ferait {serveur} et le retour {attendu} : rien n\'a été enregistré, et aucun numéro n\'est pris. Vérifie les taux de TVA et le timbre du retour',
  'boutique.ecart': 'la facture ferait {serveur} et la commande {attendu} : rien n\'a été facturé, et aucun numéro n\'est pris. Vérifie les taux de TVA et le timbre de la commande',
  'contrat.client_inconnu': 'ce n\'est pas un client de cette entreprise (lis ses clients avec GET …/clients)',
  'v10.client_manquant': 'cette facture n\'a pas de client : choisis-le avant de l\'émettre',
  'v10.ttn_par_le_serveur': 'la référence de la TTN de la pièce {numero} ne s\'écrit que par le serveur, quand la TTN l\'accepte : rien n\'a été enregistré',
  // La facture électronique (brique 80 ; docs/facture-electronique.md).
  'efacture.manques': 'ton entreprise est soumise à la facture électronique, et le fichier El Fatoora de cette pièce serait refusé : {manques} Rien n\'a été émis, aucun numéro n\'a été pris',
  'efacture.ecart': 'le fichier El Fatoora ne dirait pas les montants de la pièce ({code} : {fichier} dans le fichier, {serveur} au serveur) : rien n\'a été émis',
  'efacture.absent': 'cette pièce n\'a pas de fichier El Fatoora écrit par le serveur',
  // La signature DigiGo (brique 81).
  'efacture.signature_indisponible': 'la signature DigiGo n\'est pas encore branchée sur ce serveur : rien n\'a été signé',
  'efacture.sans_signataire': 'personne n\'est désigné pour signer : pose l\'identifiant DigiGo du signataire dans Paramètres → Documents',
  'efacture.sans_fichier': 'la pièce {numero} n\'a pas de fichier El Fatoora écrit par le serveur : rien n\'a été signé',
  'efacture.deja_signee': 'la pièce {numero} est déjà signée',
  'efacture.digigo_injoignable': 'DigiGo ne répond pas pour le moment : rien n\'a été signé, réessaie dans un instant',
  'efacture.digigo_refus': 'DigiGo a refusé la demande (réponse {statut}) : rien n\'a été signé',
  'efacture.code_faux': 'ce n\'est pas le code envoyé par DigiGo : il te reste {restants} essais',
  'efacture.code_faux_dernier': 'ce n\'est pas le code envoyé par DigiGo : il te reste un essai',
  'efacture.code_epuise': 'trois codes faux : cette demande est perdue, rien n\'a été signé. Recommence la signature : un nouveau code partira',
  'efacture.demande_finie': 'cette demande de signature est terminée : recommence la signature si besoin',
  'efacture.signature_fausse': 'DigiGo a rendu un fichier qui n\'est pas celui qu\'on lui a envoyé : rien n\'a été gardé',
  // L'envoi à la TTN (brique 82).
  'ttn.injoignable': 'la TTN ne répond pas pour le moment : SkanFact réessaiera tout seul',
  'ttn.panne': 'la TTN a répondu par une erreur (réponse {statut}) : SkanFact réessaiera tout seul',
  'ttn.sans_compte': 'le compte El Fatoora de l\'entreprise n\'est pas posé : branche-le dans Paramètres → Documents, et la pièce partira',
  'ttn.compte_illisible': 'le mot de passe El Fatoora ne se lit plus sur ce serveur : pose-le de nouveau dans Paramètres → Documents',
  'ttn.compte_refuse': 'la TTN refuse le compte El Fatoora de l\'entreprise (« {message} ») : vérifie l\'identifiant et le mot de passe dans Paramètres → Documents',
  'ttn.depot_refuse': 'la TTN a refusé la pièce au dépôt : « {message} »',
  'ttn.refusee': 'la TTN a refusé la pièce : {accuses}',
  'ttn.renvoi_impossible': 'seule une pièce refusée par la TTN se renvoie ; la pièce {numero} ne l\'est pas',
  'v10.ecart_montant': 'le serveur ne trouve pas le même net à payer que l\'écran ({ecran} à l\'écran, {serveur} au serveur) : rien n\'a été émis. Vérifie le timbre et les taux, puis réessaie',
});
