// Les textes du dossier v10 tenu par le serveur (14 § 5) : ses refus, et ce que font ses gestes.

import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'v10.conflit': 'quelqu\'un d\'autre vient de modifier ce dossier : recharge-le, tes changements ne sont pas perdus tant que la fenêtre reste ouverte',
  'v10.emission_par_le_serveur': 'une facture ou un avoir ne s\'émet qu\'avec le bouton « Émettre » : c\'est le serveur qui lui donne son numéro',
  'v10.avoir_ne_se_modifie_plus': 'l\'avoir {numero} est émis : il ne se modifie plus',
  'v10.avoir_ne_s_efface_pas': 'l\'avoir {numero} est émis : il ne s\'efface jamais',
  'v10.annulee': 'la facture {numero} est émise : elle ne s\'annule pas, on la corrige par un avoir (un avoir total la solde)',
  'v10.reglement_sur_brouillon': 'un paiement ne s\'enregistre que sur une facture émise : émets-la d\'abord',
  'v10.reglement_sans_identifiant': 'un paiement de la facture {numero} n\'a pas d\'identifiant : rien n\'a été enregistré',
  'v10.reglement_double': 'deux paiements de la facture {numero} portent le même identifiant : rien n\'a été enregistré',
  'v10.reglement_date': 'un paiement de la facture {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.reglement_montant': 'un paiement de la facture {numero} n\'a pas de montant : rien n\'a été enregistré',
  'v10.reglement_decimales': 'un paiement en {devise} se compte à {decimales} décimales au plus ({montant}) : rien n\'a été enregistré',
  'v10.reglement_cours': 'le taux du jour d\'un paiement de la facture {numero} est illisible : rien n\'a été enregistré',
  'v10.reglement_ailleurs': 'ce paiement appartient déjà à une autre facture : rien n\'a été enregistré',
  'v10.salarie_enfants': 'le nombre d\'enfants à charge de {salarie} doit être un nombre entier entre 0 et 99 : rien n\'a été enregistré',
  'v10.salarie_date': 'la date d\'entrée ou de sortie de {salarie} n\'est pas une date valable : rien n\'a été enregistré',
  'v10.bulletin_salarie': 'un bulletin de {periode} nomme un salarié qui n\'existe plus : rien n\'a été enregistré',
  'v10.bulletin_periode': 'un bulletin de {salarie} n\'a pas de mois valable : rien n\'a été enregistré',
  'v10.bulletin_sans_bareme': 'le bulletin de {salarie} ({periode}) n\'a pas gardé le barème qui l\'a calculé : ouvre-le et enregistre-le à nouveau. Rien n\'a été enregistré',
  'v10.bulletin_bareme': 'le barème du bulletin de {salarie} ({periode}) est illisible (un taux entre 0 et 100 à quatre décimales au plus, un montant au millime) : rien n\'a été enregistré',
  'v10.bulletin_saisie': 'le bulletin de {salarie} ({periode}) a un brut, des jours, une prime ou une retenue illisible (un montant positif au millime, des jours au millième) : rien n\'a été enregistré',
  'v10.bulletin_situation': 'le bulletin de {salarie} ({periode}) compte des enfants à charge qui ne sont pas un nombre entier entre 0 et 99 : rien n\'a été enregistré',
  'v10.bulletin_ecart': 'le serveur ne trouve pas les mêmes montants que l\'écran pour le bulletin de {salarie} ({periode}) : {montant} vaut {ecran} à l\'écran, {serveur} au serveur. Rien n\'a été enregistré',
  'v10.bulletin_brut': 'le bulletin de {salarie} ({periode}) a un salaire brut nul une fois les absences déduites : ouvre-le et corrige ses jours d\'absence, ou supprime-le. Rien n\'a été enregistré',
  'v10.bulletin_net': 'le bulletin de {salarie} ({periode}) aurait un net négatif, ses retenues dépassent le salaire : ouvre-le et réduis une retenue (une avance se rembourse sur plusieurs mois), ou supprime-le. Rien n\'a été enregistré',
  'v10.bulletin_paye_le': 'la date de paiement du bulletin de {salarie} ({periode}) n\'est pas une date valable : rien n\'a été enregistré',
  'v10.achat_reglement_sans_identifiant': 'un règlement de l\'achat {numero} n\'a pas d\'identifiant : rien n\'a été enregistré',
  'v10.achat_reglement_double': 'deux règlements de l\'achat {numero} portent le même identifiant : rien n\'a été enregistré',
  'v10.achat_reglement_date': 'un règlement de l\'achat {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.achat_reglement_montant': 'un règlement de l\'achat {numero} n\'a pas de montant : rien n\'a été enregistré',
  'v10.achat_reglement_cours': 'le taux du jour d\'un règlement de l\'achat {numero} est illisible : rien n\'a été enregistré',
  'v10.achat_reglement_ailleurs': 'ce règlement appartient déjà à un autre achat : rien n\'a été enregistré',
  'v10.achat_nature': 'l\'achat {numero} n\'est ni une facture, ni une dépense, ni un avoir, ni un acompte : rien n\'a été enregistré',
  'v10.achat_date': 'l\'achat {numero} n\'a pas de date valable : rien n\'a été enregistré',
  'v10.achat_echeance': 'l\'échéance de l\'achat {numero} n\'est pas une date valable : rien n\'a été enregistré',
  'v10.achat_devise': 'la devise {devise} de l\'achat {numero} n\'est pas encore connue du serveur : rien n\'a été enregistré',
  'v10.achat_cours': 'l\'achat {numero} est en {devise} : indique son taux de change (combien vaut 1 {devise} en dinars). Rien n\'a été enregistré',
  'v10.achat_frais': 'les frais de l\'achat {numero} en {devise} se comptent à {decimales} décimales au plus : rien n\'a été enregistré',
  'v10.achat_retenue': 'le taux de retenue de l\'achat {numero} doit être un pourcentage entre 0 et 100, à quatre décimales au plus : rien n\'a été enregistré',
  'v10.achat_ligne': 'la ligne {rang} de l\'achat {numero} a une quantité (trois décimales au plus), un prix (six) ou un taux de TVA (entre 0 et 100) illisible : rien n\'a été enregistré',
  'v10.achat_fournisseur': 'le fournisseur de l\'achat {numero} n\'existe plus : choisis-en un autre. Rien n\'a été enregistré',
  'v10.achat_lie_introuvable': 'l\'achat {numero} est rattaché à une pièce qui n\'existe plus : ouvre-le et retire le rattachement. Rien n\'a été enregistré',
  'v10.achat_lie_devise': 'l\'achat {numero} se rattache à une pièce en {devise} : un avoir ou un acompte se rattache à une pièce de SA devise. Rien n\'a été enregistré',
  'v10.achat_lie_nature': 'l\'achat {numero} se rattache à une pièce qui n\'est ni une facture ni une dépense : rien n\'a été enregistré',
  'v10.achat_rattache': 'un avoir ou un acompte est rattaché à cet achat : détache-le (ou supprime-le) d\'abord, puis supprime l\'achat. Rien n\'a été supprimé',
  'v10.emise_ne_se_modifie_plus': 'la facture {numero} est émise : elle ne se modifie plus, on la corrige par un avoir',
  'v10.emise_ne_s_efface_pas': 'la facture {numero} est émise : elle ne s\'efface jamais, on la corrige par un avoir',
  'v10.client_manquant': 'cette facture n\'a pas de client : choisis-le avant de l\'émettre',
  'v10.ecart_montant': 'le serveur ne trouve pas le même net à payer que l\'écran ({ecran} à l\'écran, {serveur} au serveur) : rien n\'a été émis. Vérifie le timbre et les taux, puis réessaie',
});
