// ÉCRIT par base/generer-types.ts à partir des migrations : ne pas le modifier à la main.
// (Un test tombe si ce fichier ne suit plus la base.)

import type { ColumnType, Generated } from 'kysely';

// Un jsonb se lit tel quel ; il s'écrit en texte JSON (JSON.stringify), jamais en objet qui
// porterait un bigint.
export type Json = unknown;

export interface BaseDeDonnees {
  'achats.ligne': {
    id: Generated<string>;
    piece: string;
    entreprise: string;
    rang: number;
    designation: string;
    quantite: bigint;
    prix_unitaire: bigint;
    taux_tva: bigint;
    destination: Generated<string>;
    non_deductible: Generated<boolean>;
    ht: bigint;
    tva: bigint;
    ttc: bigint;
  };
  'achats.piece': {
    id: Generated<string>;
    entreprise: string;
    ref_v10: string | null;
    nature: string;
    fournisseur: string | null;
    numero_fournisseur: string | null;
    date_piece: string;
    echeance: string | null;
    devise: Generated<string>;
    cours: bigint | null;
    taux_retenue: Generated<bigint>;
    frais: Generated<bigint>;
    tva_recuperable: boolean;
    lie: string | null;
    objet: string | null;
    categorie: string | null;
    total_ht: bigint;
    total_tva: bigint;
    tva_deductible: bigint;
    total_ttc: bigint;
    retenue: bigint;
    net_a_payer: bigint;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
  };
  'achats.reglement': {
    id: Generated<string>;
    entreprise: string;
    piece: string;
    ref_v10: string | null;
    rang: number;
    date_reglement: string;
    montant: bigint;
    cours: bigint | null;
    mode: string;
    compte: string | null;
    reference: string | null;
    note: string | null;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
  };
  'cabinet.fiche': {
    cabinet: string;
    entreprise: string;
    contenu: ColumnType<Json, string, string>;
    revision: Generated<bigint>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
  };
  'cabinet.reglages': {
    cabinet: string;
    contenu: ColumnType<Json, string, string>;
    revision: Generated<bigint>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
  };
  'cabinet.revision': {
    cabinet: string;
    entreprise: string;
    periode: string;
    contenu: ColumnType<Json, string, string>;
    revision: Generated<bigint>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
  };
  'compta.annuel': {
    entreprise: string;
    annee: number;
    retraitements: ColumnType<Json, string | undefined, string>;
    taux_impot: bigint | null;
    revision: Generated<bigint>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
  };
  'compta.cloture': {
    entreprise: string;
    jusqua: string;
    par: string | null;
    le: Generated<Date>;
  };
  'compta.compteur': {
    entreprise: string;
    journal: string;
    annee: number;
    dernier: bigint;
  };
  'compta.declaration': {
    id: Generated<string>;
    entreprise: string;
    type: Generated<string>;
    periode: string;
    cases: ColumnType<Json, string, string>;
    preparee_par: string | null;
    preparee_le: Generated<Date>;
    deposee_le: string | null;
    deposee_par: string | null;
    deposee_reference: Generated<string>;
    payee_le: string | null;
    payee_par: string | null;
    ecriture: string | null;
  };
  'compta.ecriture': {
    id: Generated<string>;
    entreprise: string;
    journal: string;
    date_ecriture: string;
    origine_type: string;
    origine: string;
    famille: string;
    rang: Generated<number>;
    piece: string | null;
    tiers: string | null;
    libelle: string;
    statut: Generated<string>;
    numero: string | null;
    cree_le: Generated<Date>;
    chaine_rang: bigint | null;
    empreinte: string | null;
    saisie_par: string | null;
    revision: Generated<number>;
    validee_par: string | null;
    validee_le: Date | null;
  };
  'compta.exercice': {
    entreprise: string;
    annee: number;
    du: string;
    au: string;
    ouverture: string | null;
    ouvert_par: string | null;
    ouvert_le: Generated<Date>;
    clos_le: Date | null;
    clos_par: string | null;
    jusqua_avant: string | null;
  };
  'compta.immobilisation': {
    id: Generated<string>;
    entreprise: string;
    fiche: ColumnType<Json, string, string>;
    revision: Generated<bigint>;
    cree_par: string | null;
    cree_le: Generated<Date>;
    modifie_le: Generated<Date>;
  };
  'compta.immobilisation_ecriture': {
    immobilisation: string;
    annee: number;
    genre: string;
    ecriture: string;
    entreprise: string;
  };
  'compta.inventaire': {
    entreprise: string;
    annee: number;
    date_inventaire: string;
    compte: string;
    lignes: ColumnType<Json, string, string>;
    total: bigint;
    ecriture: string | null;
    saisi_par: string | null;
    saisi_le: Generated<Date>;
  };
  'compta.lettrage': {
    id: Generated<string>;
    entreprise: string;
    compte: string;
    lettre: string;
    rang: bigint | null;
    cree_par: string | null;
    cree_le: Generated<Date>;
  };
  'compta.ligne': {
    id: Generated<string>;
    ecriture: string;
    entreprise: string;
    rang: number;
    compte: string;
    libelle: string;
    debit: Generated<bigint>;
    credit: Generated<bigint>;
    taux_tva: bigint | null;
    tiers_libelle: string | null;
  };
  'compta.ligne_lettree': {
    ligne: string;
    lettrage: string;
    entreprise: string;
  };
  'compta.question': {
    id: Generated<string>;
    entreprise: string;
    cabinet: string | null;
    periode: string;
    cycle: Generated<string>;
    compte: Generated<string>;
    ecriture: string | null;
    piece: Generated<string>;
    montant: Generated<bigint>;
    objet: Generated<string>;
    texte: string;
    attendu: Generated<string>;
    statut: Generated<string>;
    envois: Generated<Date[]>;
    reponse: string | null;
    repondu_par: string | null;
    repondu_le: Date | null;
    pose_par: string | null;
    pose_le: Generated<Date>;
    close_par: string | null;
    close_le: Date | null;
  };
  'compta.rapprochement': {
    releve_ligne: string;
    ligne: string;
    entreprise: string;
    niveau: string;
    auto: Generated<boolean>;
    pose_par: string | null;
    pose_le: Generated<Date>;
  };
  'compta.releve': {
    id: Generated<string>;
    entreprise: string;
    annee: number;
    compte: string;
    banque: Generated<string>;
    du: string;
    au: string;
    solde_debut: bigint;
    solde_fin: bigint;
    fichier: Generated<string>;
    empreinte: string;
    importe_par: string | null;
    importe_le: Generated<Date>;
  };
  'compta.releve_ligne': {
    id: Generated<string>;
    releve: string;
    entreprise: string;
    rang: number;
    date_operation: string;
    libelle: Generated<string>;
    reference: Generated<string>;
    montant: bigint;
    niveau: Generated<string>;
  };
  'compta.reouverture': {
    id: Generated<string>;
    entreprise: string;
    annee: number;
    clos_le: Date;
    clos_par: string | null;
    rouvert_le: Generated<Date>;
    rouvert_par: string | null;
    motif: string;
  };
  'paie.bulletin': {
    id: Generated<string>;
    entreprise: string;
    ref_v10: string | null;
    salarie: string;
    annee: number;
    mois: number;
    brut_de_base: bigint;
    jours_ouvrables: bigint;
    jours_absence: Generated<bigint>;
    primes: ColumnType<Json, string | undefined, string>;
    retenues: ColumnType<Json, string | undefined, string>;
    contrat: string | null;
    chef_de_famille: boolean;
    enfants: number;
    bareme: ColumnType<Json, string, string>;
    retenue_absence: bigint;
    primes_imposables: bigint;
    primes_non_imposables: bigint;
    brut: bigint;
    assiette_cnss: bigint;
    cnss_salarie: bigint;
    frais_pro: bigint;
    deductions_famille: bigint;
    imposable_annuel: bigint;
    irpp_annuel: bigint;
    irpp: bigint;
    css: bigint;
    autres_retenues: bigint;
    net: bigint;
    cnss_employeur: bigint;
    accident_travail: bigint;
    tfp: bigint;
    foprolos: bigint;
    charges_patronales: bigint;
    cout_employeur: bigint;
    paye_le: string | null;
    mode: string | null;
    compte: string | null;
    reference: string | null;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
  };
  'paie.salarie': {
    id: Generated<string>;
    entreprise: string;
    ref_v10: string | null;
    nom: string;
    numero_cnss: string | null;
    poste: string | null;
    contrat: string | null;
    chef_de_famille: Generated<boolean>;
    enfants: Generated<number>;
    date_entree: string | null;
    date_sortie: string | null;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
  };
  'socle.abonnement_avis': {
    id: Generated<string>;
    entreprise: string;
    url: string;
    evenements: string[];
    secret: string;
    cree_par: string;
    cree_le: Generated<Date>;
    arrete_le: Date | null;
    arrete_par: string | null;
  };
  'socle.appareil': {
    id: Generated<string>;
    utilisateur: string;
    nom: string;
    type: string;
    premier_vu: Generated<Date>;
    dernier_vu: Date | null;
    reconnu_jusqu_au: Date | null;
    revoque_le: Date | null;
    cle_publique: string | null;
  };
  'socle.audit': {
    id: Generated<string>;
    instant: Generated<Date>;
    entreprise: string | null;
    utilisateur: string | null;
    appareil: string | null;
    geste: string;
    objet_type: string | null;
    objet_id: string | null;
    avant: ColumnType<Json | null, string | null, string | null>;
    apres: ColumnType<Json | null, string | null, string | null>;
    lecture: Generated<boolean>;
    cle_api: string | null;
  };
  'socle.avis': {
    id: Generated<string>;
    entreprise: string;
    abonnement: string;
    evenement: string;
    corps: ColumnType<Json, string, string>;
    cree_le: Generated<Date>;
    essais: Generated<number>;
    prochain_essai: Generated<Date>;
    livre_le: Date | null;
    abandonne_le: Date | null;
    dernier_statut: number | null;
    derniere_erreur: string | null;
  };
  'socle.chaine': {
    entreprise: string;
    cle: string;
    rang: Generated<bigint>;
    derniere: Generated<string>;
    controle_le: Date | null;
    controle_ok: boolean | null;
  };
  'socle.cle_api': {
    id: Generated<string>;
    entreprise: string;
    nom: string;
    prefixe: string;
    empreinte: string;
    gestes: string[];
    cree_par: string;
    cree_le: Generated<Date>;
    expire_le: Date;
    revoquee_le: Date | null;
    revoquee_par: string | null;
    derniere_utilisation: Date | null;
  };
  'socle.code_secours': {
    id: Generated<string>;
    utilisateur: string;
    empreinte: string;
    utilise_le: Date | null;
  };
  'socle.compteur': {
    serie: string;
    entreprise: string;
    periode: number;
    dernier: bigint;
    repris: bigint | null;
  };
  'socle.defi_connexion': {
    id: Generated<string>;
    utilisateur: string;
    appareil: string | null;
    methode: string;
    code_empreinte: string | null;
    cree_le: Date;
    expire_le: Date;
    erreurs: Generated<number>;
    resolu_le: Date | null;
  };
  'socle.devise': {
    code: string;
    symbole: string;
    decimales: number;
    nom: string;
  };
  'socle.dossier_v10': {
    entreprise: string;
    collection: string;
    cle: string;
    contenu: ColumnType<Json, string, string>;
    rang: number | null;
    revision: Generated<bigint>;
    modifie_le: Generated<Date>;
    modifie_par: string | null;
  };
  'socle.entreprise': {
    id: Generated<string>;
    organisation: string;
    raison_sociale: string;
    forme_juridique: string | null;
    matricule_fiscal: string | null;
    devise_base: Generated<string>;
    fuseau: Generated<string>;
    debut_exercice_mois: Generated<number>;
    debut_sur_skanfact: Generated<string>;
    active: Generated<boolean>;
    cree_le: Generated<Date>;
    essai: Generated<boolean>;
    tenue_par: string | null;
  };
  'socle.etablissement': {
    id: Generated<string>;
    entreprise: string;
    code: string;
    nom: string;
    type: Generated<string>;
    actif: Generated<boolean>;
    cree_le: Generated<Date>;
  };
  'socle.file_appareil': {
    appareil: string;
    utilisateur: string;
    dernier_ordre: Generated<bigint>;
  };
  'socle.invitation': {
    id: Generated<string>;
    entreprise: string | null;
    email: string;
    roles: string[];
    jeton_empreinte: string;
    invite_par: string;
    cree_le: Generated<Date>;
    expire_le: Date;
    acceptee_le: Date | null;
    annulee_le: Date | null;
    organisation: string | null;
  };
  'socle.maillon': {
    entreprise: string;
    cle: string;
    rang: bigint;
    objet_type: string;
    objet_id: string;
    contenu: string;
    precedente: string;
    empreinte: string;
    instant: Generated<Date>;
  };
  'socle.mandat': {
    id: Generated<string>;
    cabinet: string;
    entreprise: string;
    accorde_par: string | null;
    debut: string;
    fin: string | null;
    perimetre: Generated<string[]>;
    statut: Generated<string>;
    cree_le: Generated<Date>;
  };
  'socle.mandat_affectation': {
    mandat: string;
    membre: string;
    role: string;
  };
  'socle.membre': {
    id: Generated<string>;
    utilisateur: string;
    organisation: string | null;
    entreprise: string | null;
    roles: string[];
    etablissements: Generated<string[]>;
    actif: Generated<boolean>;
    invite_par: string | null;
    depuis: Generated<Date>;
  };
  'socle.migration': {
    numero: number;
    nom: string;
    empreinte: string;
    appliquee_le: Generated<Date>;
  };
  'socle.operation': {
    id: string;
    appareil: string;
    utilisateur: string;
    entreprise: string | null;
    ordre: bigint;
    geste: string;
    format: number;
    revision_vue: bigint | null;
    instant_poste: Date;
    recu_le: Generated<Date>;
    horloge_ecartee: Generated<boolean>;
    charge: ColumnType<Json, string, string>;
    statut: string;
    motif: string | null;
    resultat: ColumnType<Json | null, string | null, string | null>;
    resolue_le: Date | null;
    resolue_par: string | null;
    resolution: string | null;
  };
  'socle.organisation': {
    id: Generated<string>;
    type: string;
    nom: string;
    code_cabinet: string | null;
    cree_le: Generated<Date>;
  };
  'socle.quarantaine': {
    id: Generated<string>;
    entreprise: string;
    session: string;
    appareil: string;
    appareil_nom: string;
    utilisateur: string;
    recue_le: Date;
    changements: ColumnType<Json, string, string>;
    decision: string | null;
    decidee_le: Date | null;
    decidee_par: string | null;
    mis_de_cote: ColumnType<Json | null, string | null, string | null>;
  };
  'socle.regle_entreprise': {
    id: Generated<string>;
    entreprise: string;
    code: string;
    valeur: ColumnType<Json, string, string>;
    debut: string;
    fin: string | null;
    motif: string;
    cree_par: string;
    cree_le: Generated<Date>;
  };
  'socle.regle_fiscale': {
    id: Generated<string>;
    code: string;
    valeur: ColumnType<Json, string, string>;
    debut: string;
    fin: string | null;
    source: string;
    verifiee_par: string | null;
    verifiee_le: string | null;
    cree_le: Generated<Date>;
  };
  'socle.serie': {
    id: Generated<string>;
    entreprise: string;
    etablissement: string | null;
    type: string;
    prefixe: string;
    remise: Generated<string>;
    format: Generated<string>;
    legale: boolean;
    active: Generated<boolean>;
    cree_le: Generated<Date>;
  };
  'socle.session': {
    id: Generated<string>;
    utilisateur: string;
    appareil: string | null;
    jeton_empreinte: string;
    ouverte_le: Date;
    derniere_activite: Date;
    inaction_max: string;
    poste_d_un_autre: Generated<boolean>;
    code_a_configurer: Generated<boolean>;
    fermee_le: Date | null;
    ip: string | null;
  };
  'socle.tentative': {
    cle: string;
    erreurs: Generated<number>;
    attente_jusqu_au: Date | null;
    derniere: Date | null;
  };
  'socle.tiers': {
    id: Generated<string>;
    entreprise: string;
    nature: Generated<string>;
    raison_sociale: string;
    identifiant: string | null;
    type_identifiant: string | null;
    adresse: string | null;
    pays: Generated<string>;
    email: string | null;
    telephone: string | null;
    devise: Generated<string>;
    roles: Generated<string[]>;
    revision: Generated<bigint>;
    cree_le: Generated<Date>;
    modifie_le: Generated<Date>;
    ref_v10: string | null;
  };
  'socle.transfert_propriete': {
    id: Generated<string>;
    entreprise: string;
    de: string;
    vers: string;
    demande_le: Generated<Date>;
    accepte_le: Date | null;
    annule_le: Date | null;
  };
  'socle.utilisateur': {
    id: Generated<string>;
    email: string;
    nom: string;
    telephone: string | null;
    telephone_verifie_le: Date | null;
    langue: Generated<string>;
    empreinte_mot_de_passe: string | null;
    cree_le: Generated<Date>;
    code_methode: string | null;
    code_secret: string | null;
  };
  'ventes.efacture': {
    piece: string;
    entreprise: string;
    nom: string;
    xml: string;
    empreinte: string;
    version: string;
    ecrit_le: Date;
    ecrit_par: string;
  };
  'ventes.efacture_signee': {
    piece: string;
    entreprise: string;
    xml: string;
    empreinte: string;
    titulaire: string | null;
    demande: string;
    signe_le: Date;
    signe_par: string;
  };
  'ventes.envoi_ttn': {
    piece: string;
    entreprise: string;
    statut: Generated<string>;
    essais: Generated<number>;
    prochain_essai: Date;
    bail: Date | null;
    depose_le: Date | null;
    id_ttn: string | null;
    reference: string | null;
    qr: string | null;
    xml_valide: string | null;
    accepte_le: Date | null;
    motif: ColumnType<Json | null, string | null, string | null>;
    cree_le: Date;
    cree_par: string;
  };
  'ventes.lien': {
    id: Generated<string>;
    entreprise: string;
    client_v10: string;
    piece_v10: string | null;
    jeton_empreinte: string;
    cree_par: string;
    cree_le: Date;
    revoque_le: Date | null;
    revoque_par: string | null;
    vu_le: Date | null;
    vues: Generated<number>;
    canal: string | null;
  };
  'ventes.ligne': {
    id: Generated<string>;
    piece: string;
    entreprise: string;
    rang: number;
    designation: string;
    description: string | null;
    quantite: bigint;
    prix_unitaire: bigint;
    taux_tva: bigint;
    sans_remise: Generated<boolean>;
    ht: bigint | null;
    tva: bigint | null;
    ttc: bigint | null;
  };
  'ventes.paiement_en_ligne': {
    id: Generated<string>;
    entreprise: string;
    piece: string;
    prestataire: string;
    montant: bigint;
    devise: string;
    retour_empreinte: string;
    cree_le: Date;
    ref: string | null;
    adresse: string | null;
    statut: Generated<string>;
    prouve_le: Date | null;
    encaisse_le: Date | null;
    reglement_v10: string | null;
    motif: ColumnType<Json | null, string | null, string | null>;
  };
  'ventes.piece': {
    id: Generated<string>;
    entreprise: string;
    type: string;
    statut: Generated<string>;
    tiers: string;
    date_piece: string;
    echeance: string | null;
    devise: Generated<string>;
    cours: bigint | null;
    taux_remise: Generated<bigint>;
    taux_retenue: Generated<bigint>;
    appliquer_timbre: boolean | null;
    objet: string | null;
    notes: string | null;
    serie: string | null;
    numero: bigint | null;
    numero_texte: string | null;
    total_ht: bigint | null;
    remise: bigint | null;
    net_ht: bigint | null;
    total_tva: bigint | null;
    timbre: bigint | null;
    timbre_base: bigint | null;
    total_ttc: bigint | null;
    retenue: bigint | null;
    net_a_payer: bigint | null;
    tva_par_taux: ColumnType<Json | null, string | null, string | null>;
    copie: ColumnType<Json | null, string | null, string | null>;
    chaine_rang: bigint | null;
    empreinte: string | null;
    emise_le: Date | null;
    emise_par: string | null;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
    ref_v10: string | null;
    corrige: string | null;
  };
  'ventes.prestataire': {
    entreprise: string;
    prestataire: string;
    portefeuille: string;
    cle_scellee: string;
    cle_fin: string;
    compte_v10: string;
    pose_le: Date;
    pose_par: string;
    dernier_refus: ColumnType<Json | null, string | null, string | null>;
    dernier_refus_le: Date | null;
  };
  'ventes.reglement': {
    id: Generated<string>;
    entreprise: string;
    piece: string;
    ref_v10: string | null;
    rang: number;
    date_reglement: string;
    montant: bigint;
    cours: bigint | null;
    mode: string;
    compte: string | null;
    reference: string | null;
    note: string | null;
    cree_par: string;
    cree_le: Generated<Date>;
    modifie_par: string | null;
    modifie_le: Generated<Date>;
    revision: Generated<bigint>;
  };
  'ventes.signataire': {
    entreprise: string;
    identifiant: string;
    pose_le: Date;
    pose_par: string;
  };
  'ventes.signature_demande': {
    id: Generated<string>;
    entreprise: string;
    pieces: string[];
    identifiant: string;
    session: string;
    titulaire: string | null;
    statut: Generated<string>;
    essais: Generated<number>;
    motif: ColumnType<Json | null, string | null, string | null>;
    cree_le: Date;
    cree_par: string;
  };
  'ventes.ttn_compte': {
    entreprise: string;
    identifiant: string;
    mot_de_passe_scelle: string;
    pose_le: Date;
    pose_par: string;
    dernier_refus: ColumnType<Json | null, string | null, string | null>;
    dernier_refus_le: Date | null;
  };
}
