// Les phrases que la BASE écrit elle-même (socle.refus, les règles des tables, les motifs du
// contrôle de la chaîne), mot pour mot, et la clé du catalogue qui les dit. Une migration appliquée
// ne se réécrit jamais : la base garde sa phrase, le serveur la reconnaît et la rend dans la langue
// de la personne, avec le texte du catalogue (qui peut dire mieux : sans renvoi aux documents).
// Un test tombe si une phrase de la base n'est pas ici, ou si une ligne d'ici n'est plus dans la base.

import { declarerTextes, t, type Texte } from './textes.ts';

type MessageDeLaBase = { base: string; cle: string; fr: string; valeurs?: string[] };

// `base` : la phrase exacte (un « %s » y tient la place d'une valeur, dans l'ordre de `valeurs`).
export const MESSAGES_DE_LA_BASE: MessageDeLaBase[] = [
  { base: 'personne n\'est connecté : impossible de créer une entreprise', cle: 'base.entreprise.sans_personne', fr: 'personne n\'est connecté : impossible de créer une entreprise' },
  { base: 'ce code n\'est plus valable : recommence la connexion', cle: 'base.connexion.code_perime', fr: 'ce code n\'est plus valable : recommence la connexion' },
  { base: 'personne ne change le mot de passe d\'un autre', cle: 'base.connexion.mot_de_passe_autre', fr: 'personne ne change le mot de passe d\'un autre' },
  { base: 'personne n\'est connecté', cle: 'base.connexion.personne', fr: 'personne n\'est connecté' },
  { base: 'il faut 10 codes de secours', cle: 'base.connexion.codes_secours', fr: 'il faut 10 codes de secours' },
  { base: 'la trace ne se modifie pas et ne s\'efface pas (01 R10)', cle: 'base.trace.intouchable', fr: 'la trace ne se modifie pas et ne s\'efface pas' },
  { base: 'ton rôle ne permet pas d\'inviter quelqu\'un dans l\'équipe', cle: 'base.equipe.inviter_interdit', fr: 'ton rôle ne permet pas d\'inviter quelqu\'un dans l\'équipe' },
  { base: 'tu ne peux pas donner ce rôle', cle: 'base.equipe.role_interdit', fr: 'tu ne peux pas donner ce rôle' },
  { base: 'personne ne s\'invite soi-même', cle: 'base.equipe.soi_meme', fr: 'personne ne s\'invite soi-même' },
  { base: 'cette invitation n\'est plus valable : demande-en une nouvelle', cle: 'base.equipe.invitation_perimee', fr: 'cette invitation n\'est plus valable : demande-en une nouvelle' },
  { base: 'cette invitation a été envoyée à une autre adresse', cle: 'base.equipe.invitation_autre_adresse', fr: 'cette invitation a été envoyée à une autre adresse' },
  { base: 'tu es le propriétaire de cette entreprise : ton rôle ne change pas par une invitation', cle: 'base.equipe.proprietaire_invite', fr: 'tu es le propriétaire de cette entreprise : ton rôle ne change pas par une invitation' },
  { base: 'membre introuvable', cle: 'base.equipe.membre_introuvable', fr: 'membre introuvable' },
  { base: 'personne ne change son propre rôle', cle: 'base.equipe.propre_role', fr: 'personne ne change son propre rôle' },
  { base: 'le rôle du propriétaire ne se change pas : il se transfère', cle: 'base.equipe.role_proprietaire', fr: 'le rôle du propriétaire ne se change pas : il se transfère' },
  { base: 'on ne retire pas le propriétaire : il transfère d\'abord la propriété', cle: 'base.equipe.retirer_proprietaire', fr: 'on ne retire pas le propriétaire : il transfère d\'abord la propriété' },
  { base: 'ton rôle ne permet pas de retirer un membre', cle: 'base.equipe.retirer_interdit', fr: 'ton rôle ne permet pas de retirer un membre' },
  { base: 'ton rôle ne permet pas de retirer un administrateur', cle: 'base.equipe.retirer_administrateur', fr: 'ton rôle ne permet pas de retirer un administrateur' },
  { base: 'seul le propriétaire transfère la propriété', cle: 'base.equipe.transfert_proprietaire', fr: 'seul le propriétaire transfère la propriété' },
  { base: 'la propriété se transfère à un membre de l\'équipe', cle: 'base.equipe.transfert_membre', fr: 'la propriété se transfère à un membre de l\'équipe' },
  { base: 'tu es déjà le propriétaire', cle: 'base.equipe.deja_proprietaire', fr: 'tu es déjà le propriétaire' },
  { base: 'ce transfert n\'est plus valable', cle: 'base.equipe.transfert_perime', fr: 'ce transfert n\'est plus valable' },
  { base: 'une règle ne s\'efface pas : on ferme sa date de fin', cle: 'base.regles.effacer', fr: 'une règle ne s\'efface pas : on ferme sa date de fin' },
  { base: 'une règle ne se modifie pas : on ferme sa date de fin et on en écrit une nouvelle', cle: 'base.regles.modifier', fr: 'une règle ne se modifie pas : on ferme sa date de fin et on en écrit une nouvelle' },
  { base: 'ton rôle ne permet pas de modifier les réglages fiscaux', cle: 'base.regles.interdit', fr: 'ton rôle ne permet pas de modifier les réglages fiscaux' },
  { base: 'une règle commence déjà ce jour-là ou après : on ne réécrit pas le passé', cle: 'base.regles.passe', fr: 'une règle commence déjà ce jour-là ou après : on ne réécrit pas le passé' },
  { base: 'ton rôle ne permet pas de créer une série de numéros', cle: 'base.series.creer_interdit', fr: 'ton rôle ne permet pas de créer une série de numéros' },
  { base: 'série introuvable', cle: 'base.series.introuvable', fr: 'série introuvable' },
  { base: 'ton rôle ne permet pas de modifier une série de numéros', cle: 'base.series.modifier_interdit', fr: 'ton rôle ne permet pas de modifier une série de numéros' },
  { base: 'des numéros ont déjà été donnés dans SkanFact pour cette période : changer la suite trouerait la série', cle: 'base.series.deja_donnes', fr: 'des numéros ont déjà été donnés dans SkanFact pour cette période : changer la suite trouerait la série' },
  { base: 'cette série n\'est plus active', cle: 'base.series.inactive', fr: 'cette série n\'est plus active' },
  { base: 'le journal inaltérable ne se modifie pas et ne s\'efface pas (01 R9)', cle: 'base.journal.intouchable', fr: 'le journal inaltérable ne se modifie pas et ne s\'efface pas' },
  { base: 'entreprise introuvable', cle: 'base.entreprise.introuvable', fr: 'entreprise introuvable' },
  { base: 'maillon manquant', cle: 'base.journal.maillon_manquant', fr: 'un maillon manque' },
  { base: 'ne suit pas le maillon précédent', cle: 'base.journal.ne_suit_pas', fr: 'ce maillon ne suit pas le précédent' },
  { base: 'empreinte fausse', cle: 'base.journal.empreinte_fausse', fr: 'une empreinte est fausse' },
  { base: 'la fin de la chaîne manque', cle: 'base.journal.fin_manque', fr: 'la fin de la chaîne manque' },
  { base: 'une opération reçue ne se modifie pas et ne s\'efface pas', cle: 'base.file.intouchable', fr: 'une opération reçue ne se modifie pas et ne s\'efface pas' },
  { base: 'appareil inconnu ou révoqué', cle: 'base.file.appareil', fr: 'appareil inconnu ou révoqué' },
  { base: 'file introuvable', cle: 'base.file.introuvable', fr: 'file introuvable' },
  { base: 'l\'opération attendue porte le numéro %s', cle: 'base.file.attendue', fr: 'l\'opération attendue porte le numéro {numero}', valeurs: ['numero'] },
  { base: 'opération introuvable', cle: 'base.file.operation_introuvable', fr: 'opération introuvable' },
  { base: 'cette opération a été acceptée : il n\'y a rien à reprendre', cle: 'base.file.rien_a_reprendre', fr: 'cette opération a été acceptée : il n\'y a rien à reprendre' },
  { base: 'cette opération a déjà été reprise', cle: 'base.file.deja_reprise', fr: 'cette opération a déjà été reprise' },
  { base: 'dis en quelques mots ce qui a été fait', cle: 'base.file.dire_quoi', fr: 'dis en quelques mots ce qui a été fait' },
  { base: 'une ligne appartient à l\'entreprise de sa pièce', cle: 'base.ventes.ligne_entreprise', fr: 'une ligne appartient à l\'entreprise de sa pièce' },
  { base: 'le client appartient à l\'entreprise de la pièce', cle: 'base.ventes.client_entreprise', fr: 'le client appartient à l\'entreprise de la pièce' },
  { base: 'une pièce émise ne s\'efface jamais (01 R6)', cle: 'base.ventes.piece_effacer', fr: 'une pièce émise ne s\'efface jamais : on la corrige par un avoir' },
  { base: 'une pièce émise ne se modifie plus : on la corrige par un avoir (01 R6)', cle: 'base.ventes.piece_modifier', fr: 'une pièce émise ne se modifie plus : on la corrige par un avoir' },
  { base: 'un avoir corrige une facture de son entreprise', cle: 'base.ventes.avoir_facture', fr: 'un avoir corrige une facture de son entreprise' },
  { base: 'un règlement porte sur une facture émise de son entreprise', cle: 'base.ventes.reglement_facture', fr: 'un règlement porte sur une facture émise de son entreprise' },
  { base: 'un règlement ne change pas de facture', cle: 'base.ventes.reglement_piece', fr: 'un règlement ne change pas de facture' },
  { base: 'une ligne ne change pas de pièce', cle: 'base.ventes.ligne_piece', fr: 'une ligne ne change pas de pièce' },
  { base: 'ton rôle ne permet pas de gérer les clés de l\'API', cle: 'base.cles.interdit', fr: 'ton rôle ne permet pas de gérer les clés de l\'API' },
  { base: 'clé introuvable', cle: 'base.cles.introuvable', fr: 'clé introuvable' },
  { base: 'cette clé est déjà révoquée', cle: 'base.cles.deja_revoquee', fr: 'cette clé est déjà révoquée' },
  { base: 'ton rôle ne permet pas de gérer les avis d\'événement', cle: 'base.avis.interdit', fr: 'ton rôle ne permet pas de gérer les avis d\'événement' },
  { base: 'abonnement introuvable', cle: 'base.avis.introuvable', fr: 'abonnement introuvable' },
  { base: 'cet abonnement est déjà arrêté', cle: 'base.avis.deja_arrete', fr: 'cet abonnement est déjà arrêté' },
  { base: 'une entreprise d\'essai le reste, et une vraie ne le devient jamais', cle: 'base.essai.immuable', fr: 'une entreprise d\'essai le reste, et une vraie ne le devient jamais' },
  { base: 'tu as déjà une entreprise d\'essai', cle: 'base.essai.deja', fr: 'tu as déjà une entreprise d\'essai' },
  { base: 'le fournisseur appartient à l\'entreprise de l\'achat', cle: 'base.achats.fournisseur', fr: 'le fournisseur appartient à l\'entreprise de l\'achat' },
  { base: 'un avoir ou un acompte se rattache à une facture ou une dépense de son entreprise', cle: 'base.achats.lie', fr: 'un avoir ou un acompte se rattache à une facture ou une dépense de son entreprise' },
  { base: 'un règlement ne change pas de pièce', cle: 'base.achats.reglement_piece', fr: 'un règlement ne change pas de pièce' },
  { base: 'un règlement porte sur un achat de son entreprise', cle: 'base.achats.reglement_achat', fr: 'un règlement porte sur un achat de son entreprise' },
  { base: 'les lignes d\'une pièce émise ne se modifient plus (01 R6)', cle: 'base.ventes.lignes_emises', fr: 'les lignes d\'une pièce émise ne se modifient plus' },
  { base: 'un bulletin ne change pas de salarié', cle: 'base.paie.bulletin_salarie', fr: 'un bulletin ne change pas de salarié' },
  { base: 'un bulletin appartient à l\'entreprise de son salarié', cle: 'base.paie.bulletin_entreprise', fr: 'un bulletin appartient à l\'entreprise de son salarié' },
  { base: 'ton rôle ne permet pas de voir la masse salariale', cle: 'base.paie.masse_interdite', fr: 'ton rôle ne permet pas de voir la masse salariale' },
  { base: 'une écriture validée ne se modifie pas : elle se contre-passe', cle: 'base.compta.validee', fr: 'une écriture validée ne se modifie pas : elle se contre-passe' },
  { base: 'une ligne appartient à l\'entreprise de son écriture', cle: 'base.compta.ligne_entreprise', fr: 'une ligne appartient à l\'entreprise de son écriture' },
  { base: 'une écriture a au moins deux lignes', cle: 'base.compta.deux_lignes', fr: 'une écriture a au moins deux lignes' },
  { base: 'une écriture est équilibrée : ses débits égalent ses crédits', cle: 'base.compta.equilibre', fr: 'une écriture est équilibrée : ses débits égalent ses crédits' },
  { base: 'valider une période est réservé au propriétaire, à l\'administrateur et à la comptabilité interne', cle: 'base.compta.valider_interdit', fr: 'valider une période est réservé au propriétaire, à l\'administrateur et à la comptabilité interne' },
  { base: 'on ne valide pas une période qui n\'est pas finie', cle: 'base.compta.valider_avenir', fr: 'on ne valide pas une période qui n\'est pas finie' },
  { base: 'la période est déjà validée jusqu\'au %s', cle: 'base.compta.deja_validee', fr: 'la période est déjà validée jusqu\'au {jour}', valeurs: ['jour'] },
  { base: 'cette pièce a une écriture validée : elle se corrige par une contre-passation', cle: 'base.compta.famille_validee', fr: 'cette pièce a une écriture validée : elle se corrige par une contre-passation' },
  { base: 'seul le propriétaire de l\'entreprise choisit son cabinet', cle: 'base.cabinet.choisir_proprietaire', fr: 'seul le propriétaire de l\'entreprise choisit son cabinet' },
  { base: 'aucun cabinet n\'a ce code', cle: 'base.cabinet.code_inconnu', fr: 'aucun cabinet n\'a ce code' },
  { base: 'cette entreprise a déjà un cabinet : arrête d\'abord son mandat', cle: 'base.cabinet.deja_un_cabinet', fr: 'cette entreprise a déjà un cabinet : arrête d\'abord son mandat' },
  { base: 'seul un associé du cabinet accepte un dossier', cle: 'base.cabinet.accepter_associe', fr: 'seul un associé du cabinet accepte un dossier' },
  { base: 'ce mandat n\'attend pas d\'être accepté', cle: 'base.cabinet.pas_propose', fr: 'ce mandat n\'attend pas d\'être accepté' },
  { base: 'seuls le propriétaire de l\'entreprise et un associé du cabinet arrêtent un mandat', cle: 'base.cabinet.arreter_qui', fr: 'seuls le propriétaire de l\'entreprise et un associé du cabinet arrêtent un mandat' },
  { base: 'ce mandat est déjà arrêté', cle: 'base.cabinet.deja_arrete', fr: 'ce mandat est déjà arrêté' },
  { base: 'ce dossier, que ton cabinet tient, a %s dans ses livres : le retirer les rendrait introuvables pour tout le monde. Archive-le plutôt (sa fiche, « Dossier archivé ») : il sort des listes sans rien perdre', cle: 'base.cabinet.retirer_tenu', fr: 'ce dossier, que ton cabinet tient, a {ecritures} dans ses livres : le retirer les rendrait introuvables pour tout le monde. Archive-le plutôt (sa fiche, « Dossier archivé ») : il sort des listes sans rien perdre', valeurs: ['ecritures'] },
  { base: 'seul le propriétaire de l\'entreprise change le périmètre de son cabinet', cle: 'base.cabinet.perimetre_proprietaire', fr: 'seul le propriétaire de l\'entreprise change le périmètre de son cabinet' },
  { base: 'seul un associé du cabinet crée un dossier', cle: 'base.cabinet.dossier_associe', fr: 'seul un associé du cabinet crée un dossier' },
  { base: 'seul un associé du cabinet confie un dossier', cle: 'base.cabinet.confier_associe', fr: 'seul un associé du cabinet confie un dossier' },
  { base: 'cette personne n\'est pas de l\'équipe du cabinet', cle: 'base.cabinet.pas_de_l_equipe', fr: 'cette personne n\'est pas de l\'équipe du cabinet' },
  { base: 'valider une période est réservé à l\'associé et aux collaborateurs du cabinet', cle: 'base.compta.valider_cabinet', fr: 'valider une période est réservé à l\'associé et aux collaborateurs du cabinet' },
  { base: 'avec un mandat de comptabilité, c\'est le cabinet qui valide la période', cle: 'base.compta.valider_au_cabinet', fr: 'avec un mandat de comptabilité, c\'est le cabinet qui valide la période' },
  { base: 'avec un mandat de comptabilité, c\'est le cabinet qui valide les écritures', cle: 'base.compta.valider_ecritures_au_cabinet', fr: 'avec un mandat de comptabilité, c\'est le cabinet qui valide les écritures' },
  { base: 'ton rôle ne permet pas de saisir dans ces livres', cle: 'base.compta.saisir_interdit', fr: 'ton rôle ne permet pas de saisir dans ces livres' },
  { base: 'ton rôle ne permet pas de lettrer ces comptes', cle: 'base.compta.lettrer_interdit', fr: 'ton rôle ne permet pas de lettrer ces comptes' },
  { base: 'ton rôle ne permet pas de valider ces écritures', cle: 'base.compta.valider_ecritures_interdit', fr: 'ton rôle ne permet pas de valider ces écritures' },
  { base: 'la date manque', cle: 'base.compta.saisie_date', fr: 'la date manque' },
  { base: 'le journal manque : c\'est lui qui range l\'écriture', cle: 'base.compta.saisie_journal', fr: 'le journal manque : c\'est lui qui range l\'écriture' },
  { base: 'la période est validée jusqu\'au %s : une écriture ne s\'y écrit plus', cle: 'base.compta.saisie_periode_close', fr: 'la période est validée jusqu\'au {jour} : une écriture ne s\'y écrit plus', valeurs: ['jour'] },
  { base: 'le libellé manque : écris-le sur la pièce ou sur une ligne', cle: 'base.compta.saisie_libelle', fr: 'le libellé manque : écris-le sur la pièce ou sur une ligne' },
  { base: 'ligne %s : le compte doit être un numéro', cle: 'base.compta.saisie_compte', fr: 'ligne {ligne} : le compte doit être un numéro', valeurs: ['ligne'] },
  { base: 'ligne %s : un montant se lit en millimes, sans signe', cle: 'base.compta.saisie_montant', fr: 'ligne {ligne} : un montant se lit en millimes, sans signe', valeurs: ['ligne'] },
  { base: 'ligne %s : une ligne va au débit ou au crédit, pas les deux', cle: 'base.compta.saisie_deux_cotes', fr: 'ligne {ligne} : une ligne va au débit ou au crédit, pas les deux', valeurs: ['ligne'] },
  { base: 'ligne %s : aucun montant', cle: 'base.compta.saisie_sans_montant', fr: 'ligne {ligne} : aucun montant', valeurs: ['ligne'] },
  { base: 'débit %s ≠ crédit %s : l\'écriture ne tombe pas juste', cle: 'base.compta.saisie_desequilibre', fr: 'débit {debit} ≠ crédit {credit} : l\'écriture ne tombe pas juste', valeurs: ['debit', 'credit'] },
  { base: 'cette écriture n\'existe pas', cle: 'base.compta.ecriture_introuvable', fr: 'cette écriture n\'existe pas' },
  { base: 'cette écriture vient d\'une pièce de l\'entreprise : elle suit sa pièce, elle ne se change pas dans les livres', cle: 'base.compta.saisie_piece', fr: 'cette écriture vient d\'une pièce de l\'entreprise : elle suit sa pièce, elle ne se change pas dans les livres' },
  { base: 'ce brouillard a été changé ailleurs entre-temps : recharge-le, rien n\'a été enregistré', cle: 'base.compta.brouillard_change', fr: 'ce brouillard a été changé ailleurs entre-temps : recharge-le, rien n\'a été enregistré' },
  { base: 'cette écriture est déjà validée : elle se contre-passe, elle ne se revalide pas', cle: 'base.compta.deja_validee_ecriture', fr: 'cette écriture est déjà validée : elle se contre-passe, elle ne se revalide pas' },
  { base: 'elle est datée du %s : une écriture ne se valide pas avant son jour', cle: 'base.compta.valider_avant_son_jour', fr: 'elle est datée du {jour} : une écriture ne se valide pas avant son jour', valeurs: ['jour'] },
  { base: 'une écriture en brouillard se modifie : elle n\'a pas besoin d\'être contre-passée', cle: 'base.compta.contrepasser_brouillard', fr: 'une écriture en brouillard se modifie : elle n\'a pas besoin d\'être contre-passée' },
  { base: 'c\'est déjà une contre-passation : pour rétablir l\'écriture, saisis-la de nouveau', cle: 'base.compta.contrepasser_miroir', fr: 'c\'est déjà une contre-passation : pour rétablir l\'écriture, saisis-la de nouveau' },
  { base: 'cette écriture vient d\'une pièce de l\'entreprise : elle se corrige dans la pièce, et le serveur la contre-passe alors lui-même', cle: 'base.compta.contrepasser_piece', fr: 'cette écriture vient d\'une pièce de l\'entreprise : elle se corrige dans la pièce, et le serveur la contre-passe alors lui-même' },
  { base: 'cette écriture a déjà été contre-passée', cle: 'base.compta.deja_contrepassee', fr: 'cette écriture a déjà été contre-passée' },
  { base: 'une contre-passation ne se date pas dans l\'avenir', cle: 'base.compta.contrepasser_avenir', fr: 'une contre-passation ne se date pas dans l\'avenir' },
  { base: 'on extourne une écriture validée : un brouillard se modifie ou se supprime', cle: 'base.compta.extourner_brouillard', fr: 'on extourne une écriture validée : un brouillard se modifie ou se supprime' },
  { base: 'on extourne une écriture saisie dans les livres : une écriture née d\'une pièce suit sa pièce', cle: 'base.compta.extourner_piece', fr: 'on extourne une écriture saisie dans les livres : une écriture née d\'une pièce suit sa pièce' },
  { base: 'des à-nouveaux ne s\'extournent pas : ils ouvrent l\'exercice', cle: 'base.compta.extourner_an', fr: 'des à-nouveaux ne s\'extournent pas : ils ouvrent l\'exercice' },
  { base: 'cette écriture a déjà été extournée', cle: 'base.compta.deja_extournee', fr: 'cette écriture a déjà été extournée' },
  { base: 'cette écriture a été contre-passée : elle ne compte plus, il n\'y a rien à extourner', cle: 'base.compta.extourner_contrepassee', fr: 'cette écriture a été contre-passée : elle ne compte plus, il n\'y a rien à extourner' },
  { base: 'son extourne tomberait le %s, dans la période validée : saisis-la au premier jour ouvert', cle: 'base.compta.extourner_periode_close', fr: 'son extourne tomberait le {jour}, dans la période validée : saisis-la au premier jour ouvert', valeurs: ['jour'] },
  { base: 'le compte à lettrer doit être un numéro', cle: 'base.compta.lettrer_compte', fr: 'le compte à lettrer doit être un numéro' },
  { base: 'le lettrage relie au moins deux écritures : une facture et son règlement', cle: 'base.compta.lettrer_deux', fr: 'le lettrage relie au moins deux écritures : une facture et son règlement' },
  { base: 'une des écritures à lettrer n\'existe pas', cle: 'base.compta.lettrer_introuvable', fr: 'une des écritures à lettrer n\'existe pas' },
  { base: 'on lettre des écritures validées : un brouillard peut encore changer', cle: 'base.compta.lettrer_brouillard', fr: 'on lettre des écritures validées : un brouillard peut encore changer' },
  { base: 'aucune de ces écritures ne touche le compte %s', cle: 'base.compta.lettrer_sans_compte', fr: 'aucune de ces écritures ne touche le compte {compte}', valeurs: ['compte'] },
  { base: 'une de ces lignes est déjà lettrée : délettre-la d\'abord', cle: 'base.compta.deja_lettree', fr: 'une de ces lignes est déjà lettrée : délettre-la d\'abord' },
  { base: 'ces écritures ne se soldent pas : il reste %s', cle: 'base.compta.lettrer_ecart', fr: 'ces écritures ne se soldent pas : il reste {montant}', valeurs: ['montant'] },
  { base: 'une lettre s\'écrit de une à cinq lettres, de A à Z', cle: 'base.compta.lettre_forme', fr: 'une lettre s\'écrit de une à cinq lettres, de A à Z' },
  { base: 'la lettre %s est déjà prise', cle: 'base.compta.lettre_prise', fr: 'la lettre {lettre} est déjà prise', valeurs: ['lettre'] },
  { base: 'ce lettrage n\'existe pas', cle: 'base.compta.lettrage_introuvable', fr: 'ce lettrage n\'existe pas' },
  { base: 'une année s\'écrit sur quatre chiffres', cle: 'base.compta.exercice_annee', fr: 'une année s\'écrit sur quatre chiffres' },
  { base: 'l\'exercice %s ne peut pas commencer avant le 01/01/%s : un premier exercice de plus de douze mois se reprend en deux, l\'un par année', cle: 'base.compta.exercice_avant', fr: 'l\'exercice {annee} ne peut pas commencer avant le 01/01/{annee} : un premier exercice de plus de douze mois se reprend en deux, l\'un par année', valeurs: ['annee', 'annee'] },
  { base: 'l\'exercice %s finit le 31/12/%s : il ne peut pas commencer après', cle: 'base.compta.exercice_apres', fr: 'l\'exercice {annee} finit le 31/12/{annee} : il ne peut pas commencer après', valeurs: ['annee', 'annee'] },
  { base: 'l\'exercice %s est déjà ouvert : une balance d\'ouverture fausse se contre-passe, puis la bonne se saisit au journal AN', cle: 'base.compta.exercice_ouvert', fr: 'l\'exercice {annee} est déjà ouvert : une balance d\'ouverture fausse se contre-passe, puis la bonne se saisit au journal AN', valeurs: ['annee'] },
  { base: 'la balance d\'ouverture ne se valide pas : %s', cle: 'base.compta.exercice_ouverture', fr: 'la balance d\'ouverture ne se valide pas : {raison}', valeurs: ['raison'] },
  { base: 'ce fichier a déjà été importé le %s (%s → %s)', cle: 'base.compta.releve_deja', fr: 'ce fichier a déjà été importé le {jour} ({du} → {au})', valeurs: ['jour', 'du', 'au'] },
  { base: 'choisis le compte bancaire de ce relevé avant de l\'importer : il ne se devine pas', cle: 'base.compta.releve_compte', fr: 'choisis le compte bancaire de ce relevé avant de l\'importer : il ne se devine pas' },
  { base: 'ce relevé ne porte aucune ligne lisible', cle: 'base.compta.releve_vide', fr: 'ce relevé ne porte aucune ligne lisible' },
  { base: 'un relevé se borne à cinq mille lignes : importe-le en plusieurs fichiers', cle: 'base.compta.releve_trop', fr: 'un relevé se borne à cinq mille lignes : importe-le en plusieurs fichiers' },
  { base: 'ce relevé ne se boucle pas : %s au départ, %s de mouvements, cela fait %s — et le relevé annonce %s. Il manque %s : il manque des lignes, ou le solde de fin n\'est pas le bon', cle: 'base.compta.releve_boucle', fr: 'ce relevé ne se boucle pas : {debut} au départ, {mouvements} de mouvements, cela fait {attendu} — et le relevé annonce {fin}. Il manque {ecart} : il manque des lignes, ou le solde de fin n\'est pas le bon', valeurs: ['debut', 'mouvements', 'attendu', 'fin', 'ecart'] },
  { base: 'ce relevé n\'existe pas', cle: 'base.compta.releve_introuvable', fr: 'ce relevé n\'existe pas' },
  { base: 'cette ligne de relevé n\'existe pas', cle: 'base.compta.releve_ligne_introuvable', fr: 'cette ligne de relevé n\'existe pas' },
  { base: 'un jugement sans écriture en face est « probable », « à confirmer » ou « aucun »', cle: 'base.compta.releve_jugement', fr: 'un jugement sans écriture en face est « probable », « à confirmer » ou « aucun »' },
  { base: 'un rapprochement posé ne peut pas être « aucun » : c\'est ce que veut dire le défaire', cle: 'base.compta.releve_aucun', fr: 'un rapprochement posé ne peut pas être « aucun » : c\'est ce que veut dire le défaire' },
  { base: 'cette ligne d\'écriture ne touche pas le compte %s', cle: 'base.compta.releve_compte_face', fr: 'cette ligne d\'écriture ne touche pas le compte {compte}', valeurs: ['compte'] },
  { base: 'cette ligne d\'écriture répond déjà d\'une autre ligne de relevé : défais ce rapprochement d\'abord', cle: 'base.compta.releve_deja_prise', fr: 'cette ligne d\'écriture répond déjà d\'une autre ligne de relevé : défais ce rapprochement d\'abord' },
  { base: 'ton rôle ne permet pas de préparer les déclarations de ce dossier', cle: 'base.compta.declarer_interdit', fr: 'ton rôle ne permet pas de préparer les déclarations de ce dossier' },
  { base: 'la période d\'une déclaration mensuelle s\'écrit AAAA-MM', cle: 'base.compta.declaration_periode', fr: 'la période d\'une déclaration mensuelle s\'écrit AAAA-MM' },
  { base: 'une déclaration porte ses cases', cle: 'base.compta.declaration_cases', fr: 'une déclaration porte ses cases' },
  { base: 'la case « %s » n\'est pas une case de la déclaration', cle: 'base.compta.declaration_case_inconnue', fr: 'la case « {cas} » n\'est pas une case de la déclaration', valeurs: ['cas'] },
  { base: 'la case « %s » se donne en millimes, ou vide', cle: 'base.compta.declaration_case_montant', fr: 'la case « {cas} » se donne en millimes, ou vide', valeurs: ['cas'] },
  { base: 'la déclaration de %s est marquée déposée le %s : dé-pointe-la d\'abord si tu veux la refaire — sinon deux chiffres différents auraient porté le même dépôt', cle: 'base.compta.declaration_deposee', fr: 'la déclaration de {mois} est marquée déposée le {jour} : dé-pointe-la d\'abord si tu veux la refaire — sinon deux chiffres différents auraient porté le même dépôt', valeurs: ['mois', 'jour'] },
  { base: 'on ne pointe qu\'un dépôt ou un paiement', cle: 'base.compta.declaration_pointage', fr: 'on ne pointe qu\'un dépôt ou un paiement' },
  { base: 'aucune déclaration préparée pour cette période', cle: 'base.compta.declaration_absente', fr: 'aucune déclaration préparée pour cette période' },
  { base: 'cette déclaration n\'est pas marquée déposée : on ne paie pas ce qu\'on n\'a pas déposé', cle: 'base.compta.declaration_pas_deposee', fr: 'cette déclaration n\'est pas marquée déposée : on ne paie pas ce qu\'on n\'a pas déposé' },
  { base: 'prépare la déclaration avant d\'en écrire l\'écriture', cle: 'base.compta.declaration_a_preparer', fr: 'prépare la déclaration avant d\'en écrire l\'écriture' },
  { base: 'l\'écriture de la déclaration de %s se date dans ce mois', cle: 'base.compta.declaration_date', fr: 'l\'écriture de la déclaration de {mois} se date dans ce mois', valeurs: ['mois'] },
  { base: 'l\'écriture de cette déclaration existe déjà dans le livre : la repasser compterait la TVA du mois deux fois', cle: 'base.compta.declaration_ecrite', fr: 'l\'écriture de cette déclaration existe déjà dans le livre : la repasser compterait la TVA du mois deux fois' },
  { base: 'ton rôle ne permet pas de préparer la liasse de ce dossier', cle: 'base.compta.liasse_interdit', fr: 'ton rôle ne permet pas de préparer la liasse de ce dossier' },
  { base: 'les retraitements d\'une année sont une liste de deux cents au plus', cle: 'base.compta.retraitements_liste', fr: 'les retraitements d\'une année sont une liste de deux cents au plus' },
  { base: 'la nature de ce retraitement n\'est pas connue', cle: 'base.compta.retraitement_nature', fr: 'la nature de ce retraitement n\'est pas connue' },
  { base: 'un retraitement sans libellé ne s\'explique pas devant un contrôle', cle: 'base.compta.retraitement_libelle', fr: 'un retraitement sans libellé ne s\'explique pas devant un contrôle' },
  { base: 'le montant d\'un retraitement est positif, en millimes : c\'est la nature qui dit dans quel sens il joue', cle: 'base.compta.retraitement_montant', fr: 'le montant d\'un retraitement est positif, en millimes : c\'est la nature qui dit dans quel sens il joue' },
  { base: 'le taux d\'impôt se donne en pourcentage, entre 0 et 100', cle: 'base.compta.taux_impot', fr: 'le taux d\'impôt se donne en pourcentage, entre 0 et 100' },
  { base: 'la liasse de cette année a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré', cle: 'base.compta.annuel_change', fr: 'la liasse de cette année a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré' },
  { base: 'une immobilisation porte sa fiche', cle: 'base.compta.immo_fiche', fr: 'une immobilisation porte sa fiche' },
  { base: 'le bien n\'a pas de libellé : une ligne sans nom ne se retrouve jamais', cle: 'base.compta.immo_libelle', fr: 'le bien n\'a pas de libellé : une ligne sans nom ne se retrouve jamais' },
  { base: 'le compte d\'immobilisation manque', cle: 'base.compta.immo_compte', fr: 'le compte d\'immobilisation manque' },
  { base: 'la date de mise en service manque : c\'est elle qui fait partir l\'amortissement', cle: 'base.compta.immo_date', fr: 'la date de mise en service manque : c\'est elle qui fait partir l\'amortissement' },
  { base: 'la valeur d\'acquisition doit être positive', cle: 'base.compta.immo_valeur', fr: 'la valeur d\'acquisition doit être positive' },
  { base: 'une valeur résiduelle négative n\'existe pas', cle: 'base.compta.immo_residuelle', fr: 'une valeur résiduelle négative n\'existe pas' },
  { base: 'la valeur résiduelle ne peut pas atteindre la valeur d\'acquisition : il n\'y aurait rien à amortir', cle: 'base.compta.immo_residuelle_haute', fr: 'la valeur résiduelle ne peut pas atteindre la valeur d\'acquisition : il n\'y aurait rien à amortir' },
  { base: 'la durée d\'amortissement doit être positive', cle: 'base.compta.immo_duree', fr: 'la durée d\'amortissement doit être positive' },
  { base: 'la méthode d\'amortissement doit être linéaire ou dégressive', cle: 'base.compta.immo_methode', fr: 'la méthode d\'amortissement doit être linéaire ou dégressive' },
  { base: 'un amortissement dégressif demande son taux : il dépend de la durée et du régime, et l\'application ne le devine pas', cle: 'base.compta.immo_taux', fr: 'un amortissement dégressif demande son taux : il dépend de la durée et du régime, et l\'application ne le devine pas' },
  { base: 'un bien ne se cède pas avant d\'être mis en service', cle: 'base.compta.immo_cession_tot', fr: 'un bien ne se cède pas avant d\'être mis en service' },
  { base: 'cette immobilisation n\'existe pas', cle: 'base.compta.immo_introuvable', fr: 'cette immobilisation n\'existe pas' },
  { base: 'cette fiche a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré', cle: 'base.compta.immo_changee', fr: 'cette fiche a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré' },
  { base: 'la dotation de %s est déjà passée en écriture : ce changement la rendrait fausse. Contre-passe-la (ou supprime-la si elle est au brouillard), puis recommence', cle: 'base.compta.immo_dotation_ecrite', fr: 'la dotation de {annee} est déjà passée en écriture : ce changement la rendrait fausse. Contre-passe-la (ou supprime-la si elle est au brouillard), puis recommence', valeurs: ['annee'] },
  { base: 'la dotation de %s est passée en écriture : supprimer la fiche laisserait une dotation sans bien. Contre-passe-la d\'abord (ou supprime-la si elle est au brouillard)', cle: 'base.compta.immo_suppression_ecrite', fr: 'la dotation de {annee} est passée en écriture : supprimer la fiche laisserait une dotation sans bien. Contre-passe-la d\'abord (ou supprime-la si elle est au brouillard)', valeurs: ['annee'] },
  { base: 'rien à passer : aucune dotation ni sortie en attente sur cet exercice', cle: 'base.compta.immo_rien', fr: 'rien à passer : aucune dotation ni sortie en attente sur cet exercice' },
  { base: 'une écriture d\'immobilisation est une dotation, une reprise de subvention ou une sortie', cle: 'base.compta.immo_genre', fr: 'une écriture d\'immobilisation est une dotation, une reprise de subvention ou une sortie' },
  { base: 'les écritures d\'immobilisation de %s se datent dans cette année', cle: 'base.compta.immo_annee', fr: 'les écritures d\'immobilisation de {annee} se datent dans cette année', valeurs: ['annee'] },
  { base: 'la %s %s de « %s » est déjà passée : la repasser la compterait deux fois', cle: 'base.compta.immo_deja', fr: 'la {genre} {annee} de « {bien} » est déjà passée : la repasser la compterait deux fois', valeurs: ['genre', 'annee', 'bien'] },
  { base: 'la date de l\'inventaire manque : c\'est le dernier jour de l\'exercice', cle: 'base.compta.inv_date', fr: 'la date de l\'inventaire manque : c\'est le dernier jour de l\'exercice' },
  { base: 'l\'inventaire de %s se date dans cette année', cle: 'base.compta.inv_annee', fr: 'l\'inventaire de {annee} se date dans cette année', valeurs: ['annee'] },
  { base: 'le compte de stock de l\'inventaire manque', cle: 'base.compta.inv_compte', fr: 'le compte de stock de l\'inventaire manque' },
  { base: 'un inventaire sans une seule ligne ne dit pas « le stock est vide », il dit « rien n\'a été compté »', cle: 'base.compta.inv_vide', fr: 'un inventaire sans une seule ligne ne dit pas « le stock est vide », il dit « rien n\'a été compté »' },
  { base: 'un inventaire se borne à dix mille lignes', cle: 'base.compta.inv_trop', fr: 'un inventaire se borne à dix mille lignes' },
  { base: 'ligne %s : la désignation manque', cle: 'base.compta.inv_libelle', fr: 'ligne {ligne} : la désignation manque', valeurs: ['ligne'] },
  { base: 'ligne %s : une quantité négative ne s\'inventorie pas', cle: 'base.compta.inv_quantite', fr: 'ligne {ligne} : une quantité négative ne s\'inventorie pas', valeurs: ['ligne'] },
  { base: 'ligne %s : un coût unitaire négatif n\'existe pas', cle: 'base.compta.inv_cout', fr: 'ligne {ligne} : un coût unitaire négatif n\'existe pas', valeurs: ['ligne'] },
  { base: 'l\'inventaire de %s est déjà passé en écriture (la variation de stock) : contre-passe-la ou supprime-la, puis refais-le', cle: 'base.compta.inv_ecrit', fr: 'l\'inventaire de {annee} est déjà passé en écriture (la variation de stock) : contre-passe-la ou supprime-la, puis refais-le', valeurs: ['annee'] },
  { base: 'aucun inventaire saisi pour %s', cle: 'base.compta.inv_absent', fr: 'aucun inventaire saisi pour {annee}', valeurs: ['annee'] },
  { base: 'la variation de stock de cet exercice est déjà passée : la repasser compterait le stock deux fois', cle: 'base.compta.inv_variation_ecrite', fr: 'la variation de stock de cet exercice est déjà passée : la repasser compterait le stock deux fois' },
  { base: 'la variation de stock de %s se date dans cette année', cle: 'base.compta.inv_variation_annee', fr: 'la variation de stock de {annee} se date dans cette année', valeurs: ['annee'] },
  { base: 'ton rôle ne permet pas de réviser ce dossier', cle: 'base.cabinet.reviser_role', fr: 'ton rôle ne permet pas de réviser ce dossier' },
  { base: 'une période de révision est une année (AAAA) ou un mois (AAAA-MM)', cle: 'base.cabinet.revision_periode', fr: 'une période de révision est une année (AAAA) ou un mois (AAAA-MM)' },
  { base: 'la révision de ce dossier a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré', cle: 'base.cabinet.revision_changee', fr: 'la révision de ce dossier a été changée ailleurs entre-temps : recharge-la, rien n\'a été enregistré' },
  { base: 'seul le cabinet de l\'entreprise lui pose des questions', cle: 'base.compta.question_cabinet', fr: 'seul le cabinet de l\'entreprise lui pose des questions' },
  { base: 'une question sans texte n\'apprend rien au client', cle: 'base.compta.question_texte', fr: 'une question sans texte n\'apprend rien au client' },
  { base: 'ce que la question attend en retour n\'est pas connu', cle: 'base.compta.question_attendu', fr: 'ce que la question attend en retour n\'est pas connu' },
  { base: 'un montant se donne en millimes', cle: 'base.compta.question_montant', fr: 'un montant se donne en millimes' },
  { base: 'cette question n\'existe plus', cle: 'base.compta.question_absente', fr: 'cette question n\'existe plus' },
  { base: 'cette question a reçu sa réponse : elle ne se réécrit plus', cle: 'base.compta.question_repondue', fr: 'cette question a reçu sa réponse : elle ne se réécrit plus' },
  { base: 'cette question est déjà partie chez le client : elle se ferme, elle ne s\'efface pas', cle: 'base.compta.question_partie', fr: 'cette question est déjà partie chez le client : elle se ferme, elle ne s\'efface pas' },
  { base: 'aucune question n\'attend de réponse : il n\'y aurait rien à envoyer', cle: 'base.compta.questions_rien', fr: 'aucune question n\'attend de réponse : il n\'y aurait rien à envoyer' },
  { base: 'seule l\'entreprise répond aux questions de son cabinet', cle: 'base.compta.question_entreprise', fr: 'seule l\'entreprise répond aux questions de son cabinet' },
  { base: 'cette question est fermée : ton cabinet n\'attend plus de réponse', cle: 'base.compta.question_fermee', fr: 'cette question est fermée : ton cabinet n\'attend plus de réponse' },
  { base: 'une réponse vide ne répond à rien', cle: 'base.compta.question_reponse_vide', fr: 'une réponse vide ne répond à rien' },
  { base: 'une réponse se borne à quatre mille caractères', cle: 'base.compta.question_reponse_longue', fr: 'une réponse se borne à quatre mille caractères' },
  { base: 'au cabinet, clôturer ou rouvrir un exercice revient à l\'associé', cle: 'base.compta.cloture_associe', fr: 'au cabinet, clôturer ou rouvrir un exercice revient à l\'associé' },
  { base: 'l\'exercice %s est déjà clos depuis le %s', cle: 'base.compta.cloture_deja', fr: 'l\'exercice {annee} est déjà clos depuis le {jour}', valeurs: ['annee', 'jour'] },
  { base: 'l\'exercice %s n\'est pas fini : il se clôture à partir du %s', cle: 'base.compta.cloture_pas_fini', fr: 'l\'exercice {annee} n\'est pas fini : il se clôture à partir du {jour}', valeurs: ['annee', 'jour'] },
  { base: 'il reste %s au brouillard jusqu\'au %s : valide-les ou supprime-les, puis clôture', cle: 'base.compta.cloture_brouillards', fr: 'il reste {nombre} au brouillard jusqu\'au {jour} : valide-les ou supprime-les, puis clôture', valeurs: ['nombre', 'jour'] },
  { base: 'cet exercice n\'est pas clos', cle: 'base.compta.rouvrir_pas_clos', fr: 'cet exercice n\'est pas clos' },
  { base: 'une réouverture demande un motif : c\'est la seule trace qui expliquera pourquoi un chiffre a changé après coup', cle: 'base.compta.rouvrir_motif', fr: 'une réouverture demande un motif : c\'est la seule trace qui expliquera pourquoi un chiffre a changé après coup' },
  { base: 'un motif se dit en cinq cents caractères au plus', cle: 'base.compta.rouvrir_motif_long', fr: 'un motif se dit en cinq cents caractères au plus' },
  { base: 'la période est validée jusqu\'au %s, après la fin de l\'exercice %s : le rouvrir rouvrirait aussi ces jours-là', cle: 'base.compta.rouvrir_apres', fr: 'la période est validée jusqu\'au {jour}, après la fin de l\'exercice {annee} : le rouvrir rouvrirait aussi ces jours-là', valeurs: ['jour', 'annee'] },
  { base: 'seul un associé du cabinet invite quelqu\'un dans son équipe', cle: 'base.cabinet.inviter_associe', fr: 'seul un associé du cabinet invite quelqu\'un dans son équipe' },
  { base: 'ce rôle n\'existe pas au cabinet', cle: 'base.cabinet.role_inconnu', fr: 'ce rôle n\'existe pas au cabinet' },
  { base: 'cette personne fait déjà partie du cabinet', cle: 'base.cabinet.deja_membre', fr: 'cette personne fait déjà partie du cabinet' },
  { base: 'cette invitation n\'existe pas', cle: 'base.cabinet.invitation_absente', fr: 'cette invitation n\'existe pas' },
  { base: 'cette invitation a déjà été acceptée : retire la personne du cabinet si elle ne doit plus y être', cle: 'base.cabinet.invitation_acceptee', fr: 'cette invitation a déjà été acceptée : retire la personne du cabinet si elle ne doit plus y être' },
  { base: 'seul un associé du cabinet change son équipe', cle: 'base.cabinet.equipe_associe', fr: 'seul un associé du cabinet change son équipe' },
  { base: 'personne ne change son propre rôle, ni ne se retire soi-même : un autre associé le fait', cle: 'base.cabinet.equipe_soi', fr: 'personne ne change son propre rôle, ni ne se retire soi-même : un autre associé le fait' },
  { base: 'seul un associé du cabinet change son nom', cle: 'base.cabinet.renommer_associe', fr: 'seul un associé du cabinet change son nom' },
  { base: 'le nom du cabinet s\'écrit en un à deux cents caractères', cle: 'base.cabinet.nom_longueur', fr: 'le nom du cabinet s\'écrit en un à deux cents caractères' },
];

declarerTextes(Object.fromEntries(MESSAGES_DE_LA_BASE.map((m) => [m.cle, m.fr])));

const echapper = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const RECONNUS = MESSAGES_DE_LA_BASE.map((m) => ({ ...m, motif: new RegExp(`^${echapper(m.base).replaceAll('%s', '(.+?)')}$`) }));

// La phrase de la base → le texte du catalogue (null si elle est inconnue : un test l'empêche).
export function reconnaitre(message: string): Texte | null {
  for (const m of RECONNUS) {
    const r = m.motif.exec(message);
    if (r) return t(m.cle, Object.fromEntries((m.valeurs ?? []).map((nom, i) => [nom, r[i + 1] ?? ''])));
  }
  return null;
}
