// Les textes de l'entrée (14 § 5) : se connecter, créer son compte, le code du téléphone, la porte de
// la première fois. Chaque phrase qu'une personne lit vient du catalogue commun. Ceux de
// l'application elle-même sont ceux de la v10, dans son code repris tel quel (public/v10).
import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'ecran.explication': 'explication : {sujet}',
  'ecran.quest_ce': 'qu\'est-ce que c\'est ?',
  'ecran.fermer': 'fermer',
  'ecran.erreur_reseau': 'le serveur ne répond pas : vérifie ta connexion, puis réessaie',
  'ecran.erreur_serveur': 'le serveur a rencontré une erreur : réessaie dans un instant',
  'ecran.deconnexion': 'se déconnecter',
  'ecran.invitation.titre': 'l\'invitation n\'a pas abouti',
  'ecran.invitation.continuer': 'continuer',
  // La phrase d'accueil de la v10, sous le titre de chaque carte.
  'ecran.accueil.sous': 'tes devis, tes factures et ta gestion, en main dès aujourd\'hui',
  'ecran.champ.afficher': 'afficher',
  'ecran.champ.cacher': 'cacher',
  'ecran.champ.afficher_mdp': 'afficher le mot de passe',
  'ecran.champ.cacher_mdp': 'cacher le mot de passe',

  // La vitrine de l'entrée (lot entrée, 06/10/2026) : ce qu'est SkanFact, et une facture juste au millime.
  'ecran.vitrine.titre': 'ta gestion, juste au millime',
  'ecran.vitrine.sous': 'devis, factures, caisse, paie et comptabilité, avec ton cabinet comptable dans les mêmes données',
  'ecran.vitrine.facture': 'facture',
  'ecran.vitrine.acceptee': 'acceptée par El Fatoora',
  'ecran.vitrine.total_ht': 'total HT',
  'ecran.vitrine.tva': 'TVA 19 %',
  'ecran.vitrine.timbre': 'timbre fiscal',
  'ecran.vitrine.ttc': 'total TTC',
  'ecran.vitrine.devise': 'DT',
  'ecran.vitrine.point_ttn': 'facture électronique El Fatoora',
  'ecran.vitrine.point_cabinet': 'ton cabinet comptable dans les mêmes données',
  'ecran.vitrine.point_coupure': 'continue de marcher pendant une coupure',
  'ecran.vitrine.compte_titre': 'trois étapes, puis ta première facture',
  'ecran.vitrine.compte_sous': 'voici ce qui t\'attend, sans surprise. Le reste se règle plus tard, dans l\'application',
  // Les trois étapes de la première fois, et leur fil en haut de chaque écran.
  'ecran.etape.fil': 'les étapes',
  'ecran.etape.compte': 'ton compte',
  'ecran.etape.compte_texte': 'ton nom, ton adresse e-mail et un mot de passe : c\'est ici',
  'ecran.etape.entreprise': 'ton entreprise',
  'ecran.etape.entreprise_texte': 'son nom et son matricule fiscal, ce qui s\'imprime en haut de chaque facture ; ou une entreprise d\'essai, pour découvrir',
  'ecran.etape.securite': 'la sécurité',
  'ecran.etape.securite_texte': 'un code sur ton téléphone à chaque connexion, pour qui gère une entreprise : personne n\'entre à ta place, même avec ton mot de passe',

  'ecran.connexion.titre': 'bon retour',
  'ecran.connexion.sous': 'connecte-toi pour retrouver tes devis, tes factures et ta gestion',
  'ecran.connexion.email': 'adresse e-mail',
  'ecran.connexion.email_aide': 'celle avec laquelle tu as créé ton compte',
  'ecran.connexion.mot_de_passe': 'mot de passe',
  'ecran.connexion.mot_de_passe_aide': 'il n\'est jamais gardé en clair, pas même par nous',
  'ecran.connexion.poste_autre': 'je suis sur l\'ordinateur de quelqu\'un d\'autre',
  'ecran.connexion.poste_autre_aide': 'la session se fermera après 30 minutes sans activité, et cet appareil ne sera pas retenu',
  'ecran.connexion.bouton': 'se connecter',
  'ecran.connexion.premiere_fois': 'première fois sur SkanFact ?',
  'ecran.connexion.creer_compte': 'créer mon compte',
  'ecran.connexion.oublie': 'mot de passe oublié ?',
  'ecran.connexion.aide': 'besoin d\'aide ?',
  'ecran.connexion.chiffree': 'connexion chiffrée ; le code du téléphone protège ton compte',

  'ecran.inscription.titre': 'créer ton compte',
  'ecran.inscription.sous': 'ton compte, c\'est toi : tes entreprises viennent juste après',
  'ecran.inscription.etape': 'étape 1 sur 3',
  'ecran.inscription.nom': 'ton nom',
  'ecran.inscription.nom_aide': 'tel que ton équipe et ton comptable le liront',
  'ecran.inscription.mot_de_passe_aide': 'au moins {min} caractères ; un mot de passe déjà volé ailleurs est refusé',
  'ecran.inscription.encore_un': 'encore un caractère au moins',
  'ecran.inscription.encore': 'encore {n} caractères au moins',
  'ecran.inscription.assez': 'c\'est bon. Une phrase de quelques mots est encore plus sûre',
  'ecran.inscription.bouton': 'créer mon compte',
  'ecran.inscription.deja': 'déjà un compte ?',
  'ecran.inscription.se_connecter': 'se connecter',
  'ecran.inscription.faite': 'ton compte est créé : connecte-toi',
  'ecran.inscription.faite_dedans': 'ton compte est créé : bienvenue dans SkanFact',

  // Le mot de passe oublié (lot entrée, 06/10/2026 ; migration 0075).
  'ecran.oubli.titre': 'mot de passe oublié',
  'ecran.oubli.sous': 'donne l\'adresse de ton compte : on t\'envoie un lien pour choisir un nouveau mot de passe',
  'ecran.oubli.bouton': 'envoyer le lien',
  'ecran.oubli.envoye_titre': 'regarde tes e-mails',
  'ecran.oubli.envoye': 'si un compte SkanFact répond à {email}, un e-mail vient de partir avec un lien valable 30 minutes. Pense à regarder aussi dans les indésirables',
  'ecran.nouveau.titre': 'choisis un nouveau mot de passe',
  'ecran.nouveau.sous': 'il remplace l\'ancien, et toutes tes sessions ouvertes se ferment',
  'ecran.nouveau.code': 'code du téléphone',
  'ecran.nouveau.code_aide': 'ton compte est protégé par ce code : tape celui de ton application d\'authentification, ou l\'un de tes codes de secours',
  'ecran.nouveau.bouton': 'changer mon mot de passe',
  'ecran.nouveau.fait': 'ton mot de passe est changé : connecte-toi avec le nouveau',
  'ecran.nouveau.perime_titre': 'ce lien n\'est plus valable',
  'ecran.nouveau.perime': 'un lien sert une fois, pendant 30 minutes. Demande-en un nouveau',
  'ecran.nouveau.redemander': 'demander un nouveau lien',

  'ecran.code.titre': 'le code de ton téléphone',
  'ecran.code.application': 'ouvre ton application d\'authentification (Google Authenticator, Microsoft Authenticator…) et tape le code de SkanFact',
  'ecran.code.sms': 'nous venons de t\'envoyer un code par SMS',
  'ecran.code.champ': 'code',
  'ecran.code.champ_aide': 'six chiffres, ou l\'un de tes codes de secours',
  'ecran.code.change': 'il change toutes les 30 secondes : tape celui qui s\'affiche maintenant',
  'ecran.code.titre_secours': 'un code de secours',
  'ecran.code.sous_secours': 'tape l\'un des codes que SkanFact t\'a donnés en mettant le code en place (sur ta photo ou ton papier)',
  'ecran.code.champ_secours': 'code de secours',
  'ecran.code.secours_aide': 'chaque code de secours ne sert qu\'une fois',
  'ecran.code.perdu': 'téléphone perdu ou changé ?',
  'ecran.code.utiliser_secours': 'utiliser un code de secours',
  'ecran.code.retrouve': 'tu as retrouvé ton téléphone ?',
  'ecran.code.utiliser_telephone': 'taper le code du téléphone',
  'ecran.code.bouton': 'valider le code',
  'ecran.code.retour': 'retour à la connexion',

  'ecran.code_requis.titre': 'dernière étape : protège ton compte',
  'ecran.code_requis.aide': 'à chaque connexion, SkanFact te demandera aussi un code qui s\'affiche sur ton téléphone : sans lui, personne n\'entre à ta place, même avec ton mot de passe. C\'est demandé à qui gère une entreprise ou ses comptes. Deux minutes, une seule fois',
  'ecran.code_requis.creee': 'ton entreprise « {nom} » est créée',
  'ecran.code_requis.etape1': 'une application d\'authentification gratuite sur ton téléphone',
  'ecran.code_requis.etape2': 'tu y scannes un code QR',
  'ecran.code_requis.etape3': 'tu tapes le code qu\'elle affiche',
  'ecran.code_requis.bouton': 'mettre en place le code',
  'ecran.code_pose.titre': 'ajoute SkanFact à ton application d\'authentification',
  'ecran.code_pose.application': 'elle te donnera un code à chaque connexion. Deux minutes, une seule fois',
  'ecran.code_pose.installer': 'installe une application d\'authentification',
  'ecran.code_pose.installer_texte': 'gratuite, sur ton téléphone. Si tu en as déjà une, passe à l\'étape 2',
  'ecran.code_pose.scanner_titre': 'scanne ce code QR',
  'ecran.code_pose.qr': 'le code QR à scanner avec ton application d\'authentification',
  'ecran.code_pose.scanner': 'dans l\'application, choisis « ajouter un compte », puis scanne ce code QR',
  'ecran.code_pose.cle': 'ou tape à la main cette clé',
  'ecran.code_pose.copier': 'copier',
  'ecran.code_pose.cle_copiee': 'clé copiée',
  'ecran.code_pose.ouvrir': 'déjà sur ton téléphone ? ouvrir dans l\'application',
  'ecran.code_pose.secours_titre': 'tes codes de secours',
  'ecran.code_pose.secours': 'si tu perds ou changes de téléphone, chacun remplace une fois le code. Garde-les à part (une photo, un papier) : ils ne se montreront plus',
  'ecran.code_pose.telecharger': 'télécharger',
  'ecran.code_pose.codes_copies': 'codes de secours copiés : colle-les dans un endroit sûr',
  'ecran.code_pose.copie_impossible': 'ton navigateur refuse la copie : télécharge-les, ou recopie-les à la main',
  'ecran.code_pose.fichier': 'Tes codes de secours SkanFact, donnés le {jour}.\nChacun remplace une fois le code du téléphone. Garde ce fichier à part.',
  'ecran.code_pose.garde': 'je les ai mis de côté',
  'ecran.code_pose.garde_avant': 'mets d\'abord tes codes de secours de côté (copie-les ou télécharge-les), puis coche « je les ai mis de côté »',
  'ecran.code_pose.garde_ok': 'parfait : le code sera demandé à chaque connexion',
  'ecran.code_pose.essai': 'le code que montre l\'application',
  'ecran.code_pose.essai_aide': 'six chiffres, qui changent toutes les 30 secondes : on vérifie que ton téléphone donne le bon avant de continuer',
  'ecran.code_pose.bouton': 'vérifier et continuer',

  // La porte de la v10 (10.14.0), pour qui n'a encore aucune entreprise.
  'ecran.connecter.titre': 'relier {partenaire} à SkanFact',
  'ecran.connecter.sous': '{partenaire} te demande l\'accès à ton entreprise dans SkanFact. Rien ne se fait sans ton accord',
  'ecran.connecter.creer_sous': '{partenaire} te demande l\'accès à ton entreprise dans SkanFact. Tu n\'en as pas encore : donne son nom, puis tu pourras autoriser',
  'ecran.connecter.pourra': 'si tu acceptes, {partenaire} pourra :',
  'ecran.connecter.pour': 'pour ton entreprise {entreprise}',
  'ecran.connecter.entreprise': 'l\'entreprise à relier',
  'ecran.connecter.entreprise_aide': 'seules les entreprises dont tu es propriétaire ou administrateur, et jamais une entreprise d\'essai',
  'ecran.connecter.rien_d_autre': '{partenaire} ne pourra rien d\'autre : il ne signe aucune facture et n\'envoie rien à la TTN',
  'ecran.connecter.connexion_sous': '{partenaire} t\'envoie ici pour relier ta boutique à SkanFact : connecte-toi (ou crée ton compte), puis tu décideras de ce que tu autorises',
  'ecran.connecter.autoriser': 'autoriser',
  'ecran.connecter.refuser': 'refuser',
  'ecran.connecter.creer': 'créer mon entreprise',
  'ecran.connecter.invalide_titre': 'cette demande de connexion n\'est pas valable',
  'ecran.connecter.ouvrir_skanfact': 'ouvrir SkanFact',
  'ecran.porte.titre': 'bienvenue dans SkanFact',
  'ecran.porte.compte_cree': 'ton compte est prêt',
  'ecran.porte.deux_facons': 'deux façons de commencer, et tu peux faire l\'une puis l\'autre : l\'entreprise d\'essai reste à part, elle ne se mélange jamais à la tienne',
  'ecran.porte.recommande': 'recommandé',
  'ecran.porte.essai_titre': 'découvrir avec une entreprise d\'essai',
  'ecran.porte.essai_texte': 'une entreprise d\'exemple déjà remplie (devis, factures, achats, paie), et une visite qui en fait le tour : tu essaies tout, sans rien risquer',
  'ecran.porte.essai_puce1': 'cinq ans d\'activité, déjà remplis',
  'ecran.porte.essai_puce2': 'une visite guidée de 12 minutes',
  'ecran.porte.essai_puce3': 'elle reste une entreprise d\'essai pour toujours',
  'ecran.porte.essai_bouton': 'commencer la découverte',
  'ecran.porte.demarrer_titre': 'commencer avec mon entreprise',
  'ecran.porte.demarrer_texte': 'sa raison sociale et son matricule fiscal : ce qui s\'imprime en haut de chaque facture. Le reste se règle ensuite, quand tu en as besoin',
  'ecran.porte.demarrer_meta': 'une minute',
  'ecran.porte.demarrer_puce1': 'ta première facture dans la foulée',
  'ecran.porte.demarrer_puce2': 'pas encore de matricule ? Tu le mets plus tard',
  'ecran.porte.demarrer_bouton': 'créer mon entreprise',
  'ecran.porte.entreprise_titre': 'ton entreprise',
  'ecran.porte.entreprise_sous': 'ce qui s\'imprimera en haut de chacune de tes factures : regarde-le se dessiner à côté',
  'ecran.porte.raison': 'raison sociale',
  'ecran.porte.raison_aide': 'le nom exact de l\'entreprise, tel qu\'il est déclaré',
  'ecran.porte.raison_patente': 'en nom propre (patente) ? Écris ton nom, par exemple « Amine Gharbi »',
  'ecran.porte.raison_societe': 'une société ? Son nom avec sa forme, par exemple « Gharbi Informatique SARL »',
  'ecran.porte.matricule': 'matricule fiscal',
  'ecran.porte.matricule_aide': 'il est obligatoire sur une facture en Tunisie : si tu ne l\'as pas encore, laisse vide et complète-le avant ta première facture',
  'ecran.porte.facultatif': 'facultatif pour l\'instant',
  'ecran.porte.mf_ou': 'il est sur ta carte d\'identification fiscale (ou ta patente), sous la forme 1234567A/A/M/000. Pas encore ? Laisse vide et complète-le avant ta première facture',
  'ecran.porte.mf_ok': 'matricule complet : il s\'imprimera sur chaque facture',
  'ecran.porte.mf_debut': 'il manque la suite, écrite juste après sur ta carte : le code TVA, la catégorie et l\'établissement, par exemple /A/M/000',
  'ecran.porte.mf_faux': 'ce n\'est pas encore la forme d\'un matricule : sept chiffres, une lettre, puis le code TVA, la catégorie et l\'établissement (1234567A/A/M/000)',
  'ecran.porte.apercu': 'le haut de ta facture',
  'ecran.porte.apercu_logo': 'ton logo',
  'ecran.porte.apercu_raison': 'ta raison sociale',
  'ecran.porte.apercu_mf': 'MF',
  'ecran.porte.apercu_type': 'facture',
  'ecran.porte.apercu_note': 'l\'adresse, le logo, le RIB et le régime fiscal se règlent ensuite, dans Paramètres',
  'ecran.porte.retour': 'retour',
  'ecran.porte.creer': 'créer mon entreprise',
  // Un cabinet comptable qui arrive : son nom, puis le Cabinet.
  'ecran.porte.cabinet_lien': 'je suis un cabinet comptable',
  'ecran.porte.cabinet_titre': 'ton cabinet',
  'ecran.porte.cabinet_sous': 'tes clients te confient leurs livres depuis leur SkanFact ; ceux qui n\'y sont pas encore, tu les tiens toi-même',
  'ecran.porte.cabinet_nom': 'nom du cabinet',
  'ecran.porte.cabinet_nom_aide': 'tel que tes clients le liront quand ils te confieront leur dossier',
  'ecran.porte.cabinet_creer': 'créer mon cabinet',

  // L'ouverture (lot entrée, 06/10/2026) : ce qui est fait se coche, puis l'application arrive.
  'ecran.ouverture.entreprise_titre': 'on ouvre ton entreprise',
  'ecran.ouverture.cabinet_titre': 'on ouvre ton cabinet',
  'ecran.ouverture.un_instant': 'un instant',
  'ecran.ouverture.compte': 'ton compte est prêt',
  'ecran.ouverture.protege': 'il est protégé par le code du téléphone',
  'ecran.ouverture.entreprise': 'ton entreprise est prête',
  'ecran.ouverture.cabinet': 'ton cabinet est prêt',
  'ecran.ouverture.charge': 'tes écrans se chargent sur cet appareil',
});
