// Les textes des écrans (14 § 5) : chaque phrase qu'une personne lit vient du catalogue commun.
import { declarerTextes } from '../../textes/index.ts';

declarerTextes({
  'ecran.aide': 'aide',
  'ecran.erreur_reseau': 'le serveur ne répond pas : vérifie ta connexion, puis réessaie',
  'ecran.deconnexion': 'se déconnecter',
  'ecran.connexion.titre': 'se connecter à SkanFact',
  'ecran.connexion.email': 'adresse e-mail',
  'ecran.connexion.email_aide': 'celle avec laquelle tu as créé ton compte',
  'ecran.connexion.mot_de_passe': 'mot de passe',
  'ecran.connexion.mot_de_passe_aide': 'il n\'est jamais gardé en clair, pas même par nous',
  'ecran.connexion.poste_autre': 'je suis sur le poste de quelqu\'un d\'autre',
  'ecran.connexion.poste_autre_aide': 'la session se fermera après 30 minutes sans activité, et cet appareil ne sera pas retenu',
  'ecran.connexion.bouton': 'se connecter',
  'ecran.connexion.creer_compte': 'je n\'ai pas encore de compte',
  'ecran.inscription.titre': 'créer ton compte',
  'ecran.inscription.nom': 'ton nom',
  'ecran.inscription.nom_aide': 'tel que ton équipe le lira',
  'ecran.inscription.mot_de_passe_aide': 'au moins {min} caractères ; un mot de passe déjà volé ailleurs est refusé',
  'ecran.inscription.bouton': 'créer mon compte',
  'ecran.inscription.deja': 'j\'ai déjà un compte',
  'ecran.code.titre': 'le code de ton téléphone',
  'ecran.code.application': 'ouvre ton application d\'authentification et tape le code de SkanFact',
  'ecran.code.sms': 'nous venons de t\'envoyer un code par SMS',
  'ecran.code.champ': 'code',
  'ecran.code.champ_aide': 'six chiffres, ou l\'un de tes codes de secours',
  'ecran.code.bouton': 'valider le code',
  'ecran.entreprises.titre': 'mes entreprises',
  'ecran.entreprises.aucune': 'tu n\'as encore aucune entreprise',
  'ecran.entreprises.aucune_aide': 'crée une entreprise d\'essai pour découvrir SkanFact et son API sans rien risquer : elle vient avec des clients d\'exemple',
  'ecran.entreprises.creer_essai': 'créer une entreprise d\'essai',
  'ecran.entreprises.essai': 'essai',
  'ecran.entreprises.essai_aide': 'une entreprise d\'essai le reste : ses factures portent « ESSAI » et ne comptent pour personne',
  'ecran.code_requis.titre': 'mets en place le code sur ton téléphone',
  'ecran.code_requis.aide': 'ton rôle l\'exige : sans ce code, personne ne peut agir à ta place, même avec ton mot de passe',
  'ecran.code_requis.bouton': 'mettre en place le code',
  'ecran.code_pose.titre': 'ajoute SkanFact à ton application d\'authentification',
  'ecran.code_pose.application': 'dans ton application, ajoute un compte avec cette adresse',
  'ecran.code_pose.secours': 'tes codes de secours, à garder à part : ils ne se montreront plus',
  'ecran.code_pose.bouton': 'j\'ai noté mes codes',
});
